/**
 * Ingredient families: child canonical → parent canonical. A cook holding the child can use it
 * where the parent is asked for (and the reverse earns partial credit), so the scorer gives a
 * family hit 0.8 instead of 1. Siblings never match each other: cheddar is not mozzarella.
 *
 * Deliberately absent: tomato paste → tomato, ground ginger → ginger, ground coriander → coriander
 * (the herb), sweet potato → potato, smoked salmon → salmon and soft cheeses → cheese, because none
 * of those stand in for each other in a recipe.
 */
export const FAMILIES: Readonly<Record<string, string>> = {
  // Poultry
  'chicken breast': 'chicken',
  'chicken thigh': 'chicken',
  'chicken wing': 'chicken',
  'chicken drumstick': 'chicken',
  'chicken leg': 'chicken',
  'ground chicken': 'chicken',
  'ground turkey': 'turkey',
  'turkey breast': 'turkey',
  'duck breast': 'duck',
  'duck leg': 'duck',
  // Beef
  'ground beef': 'beef',
  'ground veal': 'veal',
  steak: 'beef',
  'sirloin steak': 'steak',
  'ribeye steak': 'steak',
  'flank steak': 'steak',
  'skirt steak': 'steak',
  'rump steak': 'steak',
  'beef tenderloin': 'beef',
  brisket: 'beef',
  'short rib': 'beef',
  // Lamb and goat
  'ground lamb': 'lamb',
  'lamb shoulder': 'lamb',
  'lamb leg': 'lamb',
  'lamb shank': 'lamb',
  'lamb chop': 'lamb',
  mutton: 'lamb',
  // Pork
  'ground pork': 'pork',
  'pork shoulder': 'pork',
  'pork belly': 'pork',
  'pork chop': 'pork',
  'pork loin': 'pork',
  'pork tenderloin': 'pork',
  'pork rib': 'pork',
  'pork knuckle': 'pork',
  pancetta: 'bacon',
  chorizo: 'sausage',
  'italian sausage': 'sausage',
  kielbasa: 'sausage',
  kabanos: 'sausage',
  merguez: 'sausage',
  // Fish and seafood
  'white fish': 'fish',
  cod: 'white fish',
  haddock: 'white fish',
  hake: 'white fish',
  pollock: 'white fish',
  monkfish: 'white fish',
  tilapia: 'white fish',
  'sea bass': 'white fish',
  snapper: 'white fish',
  barramundi: 'white fish',
  salmon: 'fish',
  tuna: 'fish',
  mackerel: 'fish',
  sardine: 'fish',
  herring: 'fish',
  trout: 'fish',
  // Eggs and dairy
  'egg yolk': 'egg',
  'egg white': 'egg',
  'heavy cream': 'cream',
  'half-and-half': 'cream',
  'greek yogurt': 'yogurt',
  ghee: 'butter',
  cheddar: 'cheese',
  mozzarella: 'cheese',
  parmesan: 'cheese',
  pecorino: 'cheese',
  feta: 'cheese',
  halloumi: 'cheese',
  'goat cheese': 'cheese',
  gruyere: 'cheese',
  emmental: 'cheese',
  'swiss cheese': 'cheese',
  gouda: 'cheese',
  brie: 'cheese',
  manchego: 'cheese',
  roumi: 'cheese',
  'monterey jack': 'cheese',
  'colby jack': 'cheese',
  'mexican cheese': 'cheese',
  vasterbottensost: 'cheese',
  'blue cheese': 'cheese',
  stilton: 'blue cheese',
  gorgonzola: 'blue cheese',
  'silken tofu': 'tofu',
  // Vegetables
  'red onion': 'onion',
  shallot: 'onion',
  'pearl onion': 'onion',
  'cherry tomato': 'tomato',
  'artichoke heart': 'artichoke',
  'roasted red pepper': 'bell pepper',
  jalapeno: 'chili',
  'scotch bonnet': 'chili',
  habanero: 'chili',
  "bird's eye chili": 'chili',
  'ancho chili': 'chili',
  'serrano chili': 'chili',
  'chestnut mushroom': 'mushroom',
  'shiitake mushroom': 'mushroom',
  'oyster mushroom': 'mushroom',
  'portobello mushroom': 'mushroom',
  'wild mushroom': 'mushroom',
  'wood ear mushroom': 'mushroom',
  porcini: 'mushroom',
  'iceberg lettuce': 'lettuce',
  'romaine lettuce': 'lettuce',
  'little gem lettuce': 'lettuce',
  'red cabbage': 'cabbage',
  'savoy cabbage': 'cabbage',
  'napa cabbage': 'cabbage',
  'butternut squash': 'squash',
  'acorn squash': 'squash',
  daikon: 'radish',
  'baby corn': 'corn',
  'snow pea': 'pea',
  'sugar snap pea': 'pea',
  'black olive': 'olive',
  'green olive': 'olive',
  'kalamata olive': 'olive',
  // Herbs, spices and seasonings
  'smoked paprika': 'paprika',
  'cumin seed': 'cumin',
  'coriander seed': 'ground coriander',
  'dijon mustard': 'mustard',
  'wholegrain mustard': 'mustard',
  'english mustard': 'mustard',
  'seven spice': 'baharat',
  'vanilla extract': 'vanilla',
  'vanilla bean': 'vanilla',
  'vanilla bean paste': 'vanilla',
  // Fruit
  'orange juice': 'orange',
  'cooking apple': 'apple',
  // Grains, pasta, bread
  'basmati rice': 'rice',
  'jasmine rice': 'rice',
  'brown rice': 'rice',
  'arborio rice': 'rice',
  'paella rice': 'rice',
  'sushi rice': 'rice',
  'glutinous rice': 'rice',
  'short grain rice': 'rice',
  'pudding rice': 'rice',
  spaghetti: 'pasta',
  linguine: 'pasta',
  fettuccine: 'pasta',
  tagliatelle: 'pasta',
  penne: 'pasta',
  rigatoni: 'pasta',
  farfalle: 'pasta',
  fusilli: 'pasta',
  macaroni: 'pasta',
  paccheri: 'pasta',
  orzo: 'pasta',
  vermicelli: 'pasta',
  'lasagna sheet': 'pasta',
  'fresh pasta': 'pasta',
  'egg pasta': 'pasta',
  'egg noodle': 'noodle',
  'rice noodle': 'noodle',
  udon: 'noodle',
  soba: 'noodle',
  'ramen noodle': 'noodle',
  'glass noodle': 'noodle',
  pita: 'bread',
  naan: 'bread',
  baguette: 'bread',
  ciabatta: 'bread',
  'sourdough bread': 'bread',
  'rye bread': 'bread',
  'bread roll': 'bread',
  'corn tortilla': 'tortilla',
  panko: 'breadcrumb',
  'self-raising flour': 'flour',
  'bread flour': 'flour',
  'whole wheat flour': 'flour',
  // Legumes
  'red lentil': 'lentil',
  'brown lentil': 'lentil',
  'green lentil': 'lentil',
  'puy lentil': 'lentil',
  'black lentil': 'lentil',
  'toor dal': 'lentil',
  'kidney bean': 'bean',
  'black bean': 'bean',
  'cannellini bean': 'bean',
  'white bean': 'bean',
  'navy bean': 'bean',
  'great northern bean': 'bean',
  'pinto bean': 'bean',
  'borlotti bean': 'bean',
  'lima bean': 'bean',
  'fava bean': 'bean',
  'black-eyed pea': 'bean',
  // Sugars and sweets
  'brown sugar': 'sugar',
  'muscovado sugar': 'brown sugar',
  'demerara sugar': 'brown sugar',
  'powdered sugar': 'sugar',
  'palm sugar': 'sugar',
  'coconut sugar': 'sugar',
  'dark chocolate': 'chocolate',
  'milk chocolate': 'chocolate',
  'chocolate chip': 'chocolate',
  'raspberry jam': 'jam',
  'strawberry jam': 'jam',
  'apricot jam': 'jam',
  'plum jam': 'jam',
  'blackcurrant jam': 'jam',
  // Nuts
  'ground almond': 'almond',
  // Oils, vinegars, stocks, wine
  'olive oil': 'oil',
  'vegetable oil': 'oil',
  'sunflower oil': 'vegetable oil',
  'canola oil': 'vegetable oil',
  'peanut oil': 'vegetable oil',
  'corn oil': 'vegetable oil',
  'grapeseed oil': 'vegetable oil',
  'coconut oil': 'oil',
  'white wine vinegar': 'vinegar',
  'red wine vinegar': 'vinegar',
  'apple cider vinegar': 'vinegar',
  'balsamic vinegar': 'vinegar',
  'rice vinegar': 'vinegar',
  'malt vinegar': 'vinegar',
  'sherry vinegar': 'vinegar',
  'chicken stock': 'stock',
  'beef stock': 'stock',
  'vegetable stock': 'stock',
  'fish stock': 'stock',
  'lamb stock': 'stock',
  'red wine': 'wine',
  'white wine': 'wine',
  'shaoxing wine': 'rice wine',
  stout: 'beer',
}

/** The helpers accept any table so tests can exercise a deliberately broken one. */
export type FamilyTable = Readonly<Record<string, string>>

export function parentOf(name: string, table: FamilyTable = FAMILIES): string | undefined {
  return Object.hasOwn(table, name) ? table[name] : undefined
}

/** Every ancestor, nearest first. A visited set keeps a bad table edit from looping forever. */
export function ancestorsOf(name: string, table: FamilyTable = FAMILIES): string[] {
  const ancestors: string[] = []
  const seen = new Set([name])
  let current = parentOf(name, table)
  while (current !== undefined && !seen.has(current)) {
    ancestors.push(current)
    seen.add(current)
    current = parentOf(current, table)
  }
  return ancestors
}

/** True when one name is an ancestor of the other. Equal names are exact, not family, matches. */
export function isFamilyMatch(a: string, b: string, table: FamilyTable = FAMILIES): boolean {
  if (a === b) return false
  return ancestorsOf(a, table).includes(b) || ancestorsOf(b, table).includes(a)
}
