import { FAMILIES } from './families'
import { STAPLES } from './staples'

/**
 * Word-level spelling fixes applied to every token before any lookup: orthographic variants and
 * typos seen in TheMealDB data, so the synonym table only has to know one spelling of each word.
 */
export const SPELLINGS: Readonly<Record<string, string>> = {
  chilli: 'chili',
  chillis: 'chilis',
  chillies: 'chilies',
  chile: 'chili',
  chiles: 'chilies',
  yoghurt: 'yogurt',
  yoghurts: 'yogurts',
  yoghourt: 'yogurt',
  yogourt: 'yogurt',
  mozarella: 'mozzarella',
  mozzerella: 'mozzarella',
  hazlenut: 'hazelnut',
  hazlenuts: 'hazelnuts',
  cardomom: 'cardamom',
  cardamon: 'cardamom',
  tumeric: 'turmeric',
  cummin: 'cumin',
  tobasco: 'tabasco',
  barbeque: 'barbecue',
  bbq: 'barbecue',
  savoury: 'savory',
  colouring: 'coloring',
  gelatine: 'gelatin',
  millk: 'milk',
  meay: 'meat',
  skirty: 'skirt',
  yolkes: 'yolks',
  filo: 'phyllo',
  fillo: 'phyllo',
  catsup: 'ketchup',
  mayo: 'mayonnaise',
  bulghur: 'bulgur',
  bulgar: 'bulgur',
  burghul: 'bulgur',
  burgul: 'bulgur',
  tahina: 'tahini',
  tehina: 'tahini',
  zaatar: "za'atar",
  zatar: "za'atar",
  zahtar: "za'atar",
  "za'tar": "za'atar",
  sumak: 'sumac',
  sumaq: 'sumac',
  houmous: 'hummus',
  humus: 'hummus',
  hommus: 'hummus',
  houmus: 'hummus',
  mulukhiyah: 'molokhia',
  mulukhiya: 'molokhia',
  molokhiya: 'molokhia',
  mloukhia: 'molokhia',
  mloukhiya: 'molokhia',
  molokheya: 'molokhia',
  melokhia: 'molokhia',
  labne: 'labneh',
  labna: 'labneh',
  haloumi: 'halloumi',
  hallumi: 'halloumi',
  freekah: 'freekeh',
  frikeh: 'freekeh',
  bamia: 'okra',
  bamya: 'okra',
  kunafa: 'knafeh',
  kunafeh: 'knafeh',
  kanafeh: 'knafeh',
  challot: 'shallot',
  challots: 'shallots',
  eschalot: 'shallot',
  eschalots: 'shallots',
  cassaba: 'cassava',
  lasagne: 'lasagna',
  linguini: 'linguine',
  fettucine: 'fettuccine',
  mahlab: 'mahleb',
  mahaleb: 'mahleb',
  fettuccini: 'fettuccine',
  emmentaler: 'emmental',
  emmenthal: 'emmental',
  emmenthaler: 'emmental',
  rosewater: 'rose water',
  beansprout: 'bean sprout',
  beansprouts: 'bean sprouts',
  brussel: 'brussels',
  // Egyptian English
  foul: 'ful',
  fuul: 'ful',
  basterma: 'basturma',
  bastirma: 'basturma',
  rumi: 'roumi',
  romy: 'roumi',
  roumy: 'roumi',
} as const

/**
 * Alias phrase (the English pipeline's intermediate form: lowercase, spelling-fixed, punctuation
 * removed, last word singular) → canonical name. Every value is a fixed point of
 * normalizeEnglishIngredient. US names win where UK/US differ, except coriander and chickpea.
 */
export const SYNONYMS: Readonly<Record<string, string>> = {
  // Herbs
  cilantro: 'coriander',
  'cilantro leaf': 'coriander',
  'coriander leaf': 'coriander',
  'fresh coriander': 'coriander',
  'coriander powder': 'ground coriander',
  'flat-leaf parsley': 'parsley',
  'flat leaf parsley': 'parsley',
  'italian parsley': 'parsley',
  'curly parsley': 'parsley',
  'sweet basil': 'basil',
  'dill weed': 'dill',
  'lemon grass': 'lemongrass',
  'kaffir lime leaf': 'lime leaf',
  'makrut lime leaf': 'lime leaf',
  'wild garlic leaf': 'wild garlic',
  'summer savory': 'savory',
  // Spices and seasonings
  'ground cumin': 'cumin',
  'ground cinnamon': 'cinnamon',
  'cinnamon stick': 'cinnamon',
  'cinnamon powder': 'cinnamon',
  'ground turmeric': 'turmeric',
  'turmeric powder': 'turmeric',
  'ground nutmeg': 'nutmeg',
  'ground allspice': 'allspice',
  'allspice berry': 'allspice',
  'ground cardamom': 'cardamom',
  'cardamom pod': 'cardamom',
  'cardamom seed': 'cardamom',
  'green cardamom': 'cardamom',
  'ground clove': 'clove',
  'ginger powder': 'ground ginger',
  'ginger root': 'ginger',
  'root ginger': 'ginger',
  'ginger paste': 'ginger',
  pepper: 'black pepper',
  'ground pepper': 'black pepper',
  'ground black pepper': 'black pepper',
  'black peppercorn': 'black pepper',
  peppercorn: 'black pepper',
  'kampot pepper': 'black pepper',
  'szechuan pepper': 'sichuan pepper',
  'szechuan peppercorn': 'sichuan pepper',
  'sichuan peppercorn': 'sichuan pepper',
  'salt and pepper': 'salt',
  'sea salt': 'salt',
  'kosher salt': 'salt',
  'table salt': 'salt',
  'rock salt': 'salt',
  'sea salt flake': 'salt',
  'pink himalayan salt': 'salt',
  'paprika powder': 'paprika',
  'sweet paprika': 'paprika',
  'sweet smoked paprika': 'smoked paprika',
  'smoky paprika': 'smoked paprika',
  pimenton: 'smoked paprika',
  'ground chili': 'chili powder',
  'ground fennel': 'fennel seed',
  caraway: 'caraway seed',
  cayenne: 'cayenne pepper',
  'ground red pepper': 'cayenne pepper',
  'red chili powder': 'chili powder',
  'kashmiri chili powder': 'chili powder',
  'chili flake': 'chili flakes',
  'red chili flake': 'chili flakes',
  'red pepper flake': 'chili flakes',
  'crushed red pepper': 'chili flakes',
  'crushed red pepper flake': 'chili flakes',
  'crushed chili': 'chili flakes',
  'pepper flake': 'chili flakes',
  'pul biber': 'chili flakes',
  'aleppo pepper': 'chili flakes',
  'madras curry powder': 'curry powder',
  'jamaican curry powder': 'curry powder',
  'chinese five spice powder': 'five spice powder',
  'chinese five spice': 'five spice powder',
  'five spice': 'five spice powder',
  'lebanese seven spice': 'seven spice',
  '7 spice': 'seven spice',
  'saffron thread': 'saffron',
  'saffron strand': 'saffron',
  'garlic granule': 'garlic powder',
  'ground garlic': 'garlic powder',
  'ground onion': 'onion powder',
  'dry mustard': 'mustard powder',
  'ground mustard': 'mustard powder',
  'english mustard powder': 'mustard powder',
  'yellow mustard': 'mustard',
  'american mustard': 'mustard',
  dijon: 'dijon mustard',
  'whole grain mustard': 'wholegrain mustard',
  'grainy mustard': 'wholegrain mustard',
  'vanilla essence': 'vanilla extract',
  'pure vanilla extract': 'vanilla extract',
  'vanilla pod': 'vanilla bean',
  'vanilla powder': 'vanilla',
  vanillin: 'vanilla',
  'almond essence': 'almond extract',
  'bicarbonate of soda': 'baking soda',
  'bicarbonate soda': 'baking soda',
  bicarb: 'baking soda',
  'all-purpose seasoning': 'seasoning',
  'all purpose seasoning': 'seasoning',
  cajun: 'cajun seasoning',
  jerk: 'jerk seasoning',
  'sazon goya': 'sazon',
  'kabse spice': 'kabsa spice',
  'speculaas spice mix': 'speculaas spice',
  'ground annatto': 'annatto',
  'achiote seed': 'annatto',
  'ground mahleb': 'mahleb',
  nigella: 'nigella seed',
  'black seed': 'nigella seed',
  kalonji: 'nigella seed',
  'mastic gum': 'mastic',
  basturma: 'pastirma',
  'calf liver': 'beef liver',
  'kiwi fruit': 'kiwi',
  kiwifruit: 'kiwi',
  'harissa paste': 'harissa',
  'harissa spice': 'harissa',
  'khus khus': 'poppy seed',
  'ground poppy seed': 'poppy seed',
  'sesame seed oil': 'sesame oil',
  sesame: 'sesame seed',
  'ground sugar': 'powdered sugar',
  // Vegetables
  aubergine: 'eggplant',
  'egg plant': 'eggplant',
  courgette: 'zucchini',
  'spring onion': 'green onion',
  scallion: 'green onion',
  'salad onion': 'green onion',
  capsicum: 'bell pepper',
  peppers: 'bell pepper',
  'red pepper': 'bell pepper',
  'green pepper': 'bell pepper',
  'yellow pepper': 'bell pepper',
  'orange pepper': 'bell pepper',
  'red bell pepper': 'bell pepper',
  'green bell pepper': 'bell pepper',
  'yellow bell pepper': 'bell pepper',
  'orange bell pepper': 'bell pepper',
  'sweet pepper': 'bell pepper',
  'sweet red pepper': 'bell pepper',
  'mixed pepper': 'bell pepper',
  'romano pepper': 'bell pepper',
  'pointed pepper': 'bell pepper',
  'roasted pepper': 'roasted red pepper',
  'red chili': 'chili',
  'green chili': 'chili',
  'chili pepper': 'chili',
  'red chili pepper': 'chili',
  'green chili pepper': 'chili',
  'hot pepper': 'chili',
  'thai chili': "bird's eye chili",
  'birds-eye chili': "bird's eye chili",
  'birds eye chili': "bird's eye chili",
  'jalapeno pepper': 'jalapeno',
  'scotch bonnet pepper': 'scotch bonnet',
  'habanero pepper': 'habanero',
  serrano: 'serrano chili',
  'serrano pepper': 'serrano chili',
  'sweet peppadew pepper': 'peppadew pepper',
  peppadew: 'peppadew pepper',
  'white onion': 'onion',
  'yellow onion': 'onion',
  'brown onion': 'onion',
  'spanish onion': 'onion',
  'sweet onion': 'onion',
  'purple onion': 'red onion',
  'banana shallot': 'shallot',
  'garlic clove': 'garlic',
  'garlic bulb': 'garlic',
  'garlic paste': 'garlic',
  'plum tomato': 'tomato',
  'vine tomato': 'tomato',
  'beef tomato': 'tomato',
  'beefsteak tomato': 'tomato',
  'roma tomato': 'tomato',
  'salad tomato': 'tomato',
  'heirloom tomato': 'tomato',
  'grape tomato': 'cherry tomato',
  'baby plum tomato': 'cherry tomato',
  'tomato puree': 'tomato paste',
  'tomato concentrate': 'tomato paste',
  'tomato passata': 'passata',
  'sieved tomato': 'passata',
  'sundried tomato': 'sun-dried tomato',
  'sun dried tomato': 'sun-dried tomato',
  'new potato': 'potato',
  'floury potato': 'potato',
  'waxy potato': 'potato',
  'russet potato': 'potato',
  'red potato': 'potato',
  'maris piper potato': 'potato',
  'king edward potato': 'potato',
  'jersey royal potato': 'potato',
  'charlotte potato': 'potato',
  'yukon gold potato': 'potato',
  'baking potato': 'potato',
  'white yam': 'yam',
  'celery stalk': 'celery',
  'celery stick': 'celery',
  'celery rib': 'celery',
  'rib celery': 'celery',
  'ribs celery': 'celery',
  'rib of celery': 'celery',
  'ribs of celery': 'celery',
  'english cucumber': 'cucumber',
  'button mushroom': 'mushroom',
  'white mushroom': 'mushroom',
  'cremini mushroom': 'chestnut mushroom',
  shiitake: 'shiitake mushroom',
  portobello: 'portobello mushroom',
  'cos lettuce': 'romaine lettuce',
  cos: 'romaine lettuce',
  'baby gem lettuce': 'little gem lettuce',
  'gem lettuce': 'little gem lettuce',
  'little gem': 'little gem lettuce',
  'baby gem': 'little gem lettuce',
  'salad leaf': 'salad greens',
  'mixed salad leaf': 'salad greens',
  'mixed leaf': 'salad greens',
  'mixed greens': 'salad greens',
  rocket: 'arugula',
  'wild rocket': 'arugula',
  'white cabbage': 'cabbage',
  'green cabbage': 'cabbage',
  'hispi cabbage': 'cabbage',
  'pointed cabbage': 'cabbage',
  'chinese cabbage': 'napa cabbage',
  'chinese leaf': 'napa cabbage',
  'pak choi': 'bok choy',
  'pak choy': 'bok choy',
  'bok choi': 'bok choy',
  'pak koi': 'bok choy',
  'tenderstem broccoli': 'broccoli',
  'purple sprouting broccoli': 'broccoli',
  broccolini: 'broccoli',
  'french bean': 'green bean',
  'string bean': 'green bean',
  'runner bean': 'green bean',
  'fine bean': 'green bean',
  'haricot vert': 'green bean',
  'chinese long bean': 'green bean',
  'long bean': 'green bean',
  'petit pois': 'pea',
  'garden pea': 'pea',
  'green pea': 'pea',
  mangetout: 'snow pea',
  'yellow split pea': 'split pea',
  sweetcorn: 'corn',
  'sweet corn': 'corn',
  'corn on the cob': 'corn',
  'corn cob': 'corn',
  butternut: 'butternut squash',
  'zapallo squash': 'squash',
  beetroot: 'beet',
  'daikon radish': 'daikon',
  mooli: 'daikon',
  swede: 'rutabaga',
  'fennel bulb': 'fennel',
  'white asparagus': 'asparagus',
  chard: 'swiss chard',
  'rainbow chard': 'swiss chard',
  'mung bean sprout': 'bean sprout',
  'stir-fry vegetable': 'mixed vegetable',
  'stir fry vegetable': 'mixed vegetable',
  'jute leaf': 'molokhia',
  "jew's mallow": 'molokhia',
  'grape leaf': 'vine leaf',
  'grape vine leaf': 'vine leaf',
  'pickled grape leaf': 'vine leaf',
  yuca: 'cassava',
  yucca: 'cassava',
  manioc: 'cassava',
  farine: 'cassava flour',
  // Fruit
  'lemon juice': 'lemon',
  'lemon zest': 'lemon',
  'lemon rind': 'lemon',
  'lime juice': 'lime',
  'lime zest': 'lime',
  'orange zest': 'orange',
  'orange rind': 'orange',
  'blood orange': 'orange',
  'bramley apple': 'cooking apple',
  'braeburn apple': 'apple',
  'granny smith apple': 'apple',
  'granny smith': 'apple',
  'green apple': 'apple',
  'red apple': 'apple',
  'eating apple': 'apple',
  'medjool date': 'date',
  'date syrup': 'date molasses',
  dibs: 'date molasses',
  'black lime': 'dried lime',
  'dried black lime': 'dried lime',
  loomi: 'dried lime',
  sultana: 'raisin',
  'golden raisin': 'raisin',
  'light raisin': 'raisin',
  'mixed peel': 'candied peel',
  'passion fruit pulp': 'passion fruit',
  'pomegranate seed': 'pomegranate',
  'coconut flake': 'coconut',
  'frozen mixed berry': 'mixed berry',
  // Meat and poultry
  'chicken breast fillet': 'chicken breast',
  'chicken fillet': 'chicken breast',
  'chicken breast half': 'chicken breast',
  'chicken thigh fillet': 'chicken thigh',
  'chicken mince': 'ground chicken',
  'minced chicken': 'ground chicken',
  'minced beef': 'ground beef',
  'beef mince': 'ground beef',
  mince: 'ground beef',
  'minced meat': 'ground beef',
  'minced steak': 'ground beef',
  'ground meat': 'ground beef',
  'ground chuck': 'ground beef',
  'ground sirloin': 'ground beef',
  'ground steak': 'ground beef',
  'hamburger meat': 'ground beef',
  'stewing beef': 'beef',
  'braising beef': 'beef',
  'stewing steak': 'beef',
  'beef chuck': 'beef',
  'chuck roast': 'beef',
  'mixed beef cut': 'beef',
  'beef shin': 'beef',
  'feather blade beef': 'beef',
  'hind shank': 'beef',
  'beef shank': 'beef',
  'beef brisket': 'brisket',
  'beef fillet': 'beef tenderloin',
  'fillet of beef': 'beef tenderloin',
  'fillet steak': 'steak',
  'fillet of steak': 'steak',
  'beef steak': 'steak',
  'minute steak': 'steak',
  'beef cutlet': 'steak',
  sirloin: 'sirloin steak',
  'sirloin steak tip': 'sirloin steak',
  'rib-eye steak': 'ribeye steak',
  'rib eye steak': 'ribeye steak',
  ribeye: 'ribeye steak',
  'beef flank steak': 'flank steak',
  'beef stock cube': 'beef stock',
  'beef broth': 'beef stock',
  'beef bouillon': 'beef stock',
  'beef stock concentrate': 'beef stock',
  'lamb mince': 'ground lamb',
  'minced lamb': 'ground lamb',
  'leg of lamb': 'lamb leg',
  'lamb loin chop': 'lamb chop',
  'lamb cutlet': 'lamb chop',
  'goat meat': 'goat',
  'pork mince': 'ground pork',
  'minced pork': 'ground pork',
  'pork shoulder steak': 'pork shoulder',
  'pork belly slice': 'pork belly',
  'pork fillet': 'pork tenderloin',
  'pork back rib': 'pork rib',
  'spare rib': 'pork rib',
  'baby back rib': 'pork rib',
  'pigs trotter': 'pig trotter',
  'frogs leg': 'frog leg',
  'streaky bacon': 'bacon',
  'back bacon': 'bacon',
  'smoked bacon': 'bacon',
  'bacon lardon': 'bacon',
  lardon: 'bacon',
  'deli ham': 'ham',
  'smoked ham': 'ham',
  'parma ham': 'prosciutto',
  'serrano ham': 'prosciutto',
  'jamon iberico': 'prosciutto',
  jamon: 'prosciutto',
  'pork sausage': 'sausage',
  'german sausage': 'sausage',
  'sausage meat': 'sausage',
  'italian fennel sausage': 'italian sausage',
  'polish kabanos': 'kabanos',
  morcilla: 'black pudding',
  frankfurter: 'hot dog',
  'turkey mince': 'ground turkey',
  'minced turkey': 'ground turkey',
  yolk: 'egg yolk',
  'egg wash': 'egg',
  'firm tofu': 'tofu',
  'extra firm tofu': 'tofu',
  'marinated tofu': 'tofu',
  // Fish and seafood
  'fish fillet': 'fish',
  'white fish fillet': 'white fish',
  'firm white fish': 'white fish',
  codfish: 'cod',
  'codfish bulljaw': 'salt cod',
  'red snapper': 'snapper',
  'rainbow trout': 'trout',
  pilchard: 'sardine',
  'smoked flaked salmon': 'smoked salmon',
  'tuna steak': 'tuna',
  prawn: 'shrimp',
  'king prawn': 'shrimp',
  'tiger prawn': 'shrimp',
  'jumbo shrimp': 'shrimp',
  'king shrimp': 'shrimp',
  calamari: 'squid',
  'crab meat': 'crab',
  'fish finger': 'fish stick',
  crabmeat: 'crab',
  'seafood mix': 'mixed seafood',
  'thai fish sauce': 'fish sauce',
  'seafood stock': 'fish stock',
  'shrimp stock': 'fish stock',
  // Dairy and eggs
  'unsalted butter': 'butter',
  'salted butter': 'butter',
  'clarified butter': 'ghee',
  'single cream': 'cream',
  'light cream': 'cream',
  'double cream': 'heavy cream',
  'whipping cream': 'heavy cream',
  'heavy whipping cream': 'heavy cream',
  'thickened cream': 'heavy cream',
  'half and half': 'half-and-half',
  'soured cream': 'sour cream',
  'natural yogurt': 'yogurt',
  'plain yogurt': 'yogurt',
  'greek-style yogurt': 'greek yogurt',
  'greek style yogurt': 'greek yogurt',
  'strained yogurt': 'greek yogurt',
  'sour milk': 'buttermilk',
  'sweetened condensed milk': 'condensed milk',
  'dry milk': 'milk powder',
  'dried milk': 'milk powder',
  'powdered milk': 'milk powder',
  'dry milk powder': 'milk powder',
  'soya milk': 'soy milk',
  'vegetable milk': 'plant milk',
  'sharp cheddar': 'cheddar',
  'parmigiano-reggiano': 'parmesan',
  'parmigiano reggiano': 'parmesan',
  'grana padano': 'parmesan',
  'pecorino romano': 'pecorino',
  'buffalo mozzarella': 'mozzarella',
  'goats cheese': 'goat cheese',
  "goat's cheese": 'goat cheese',
  chevre: 'goat cheese',
  'colby jack cheese': 'colby jack',
  'monterey jack cheese': 'monterey jack',
  'shredded monterey jack cheese': 'monterey jack',
  // Grains, pasta, bread
  'white rice': 'rice',
  'long grain rice': 'rice',
  'long-grain rice': 'rice',
  'long grain white rice': 'rice',
  basmati: 'basmati rice',
  'risotto rice': 'arborio rice',
  'bomba rice': 'paella rice',
  'sticky rice': 'glutinous rice',
  'dessert rice': 'pudding rice',
  'penne rigate': 'penne',
  'bowtie pasta': 'farfalle',
  'bow tie pasta': 'farfalle',
  'elbow macaroni': 'macaroni',
  'lasagna noodle': 'lasagna sheet',
  'vermicelli pasta': 'vermicelli',
  sevaiiya: 'vermicelli',
  'rice vermicelli': 'rice noodle',
  'vermicelli rice noodle': 'rice noodle',
  'flat rice noodle': 'rice noodle',
  'rice stick noodle': 'rice noodle',
  'brown rice noodle': 'rice noodle',
  'udon noodle': 'udon',
  'soba noodle': 'soba',
  'instant noodle': 'noodle',
  'white bread': 'bread',
  'crusty bread': 'bread',
  'wholegrain bread': 'bread',
  'whole wheat bread': 'bread',
  'cuban bread': 'bread',
  toast: 'bread',
  'sesame seed burger bun': 'bun',
  'burger bun': 'bun',
  pitta: 'pita',
  'pitta bread': 'pita',
  'pita bread': 'pita',
  'naan bread': 'naan',
  'flour tortilla': 'tortilla',
  'hard taco shell': 'taco shell',
  'panko breadcrumb': 'panko',
  'graham cracker crumb': 'graham cracker',
  'white bread mix': 'bread mix',
  'plain flour': 'flour',
  'all-purpose flour': 'flour',
  'all purpose flour': 'flour',
  'white flour': 'flour',
  'wheat flour': 'flour',
  'plain white flour': 'flour',
  'self raising flour': 'self-raising flour',
  'self-rising flour': 'self-raising flour',
  'self rising flour': 'self-raising flour',
  'strong white flour': 'bread flour',
  'strong flour': 'bread flour',
  'strong white bread flour': 'bread flour',
  'strong bread flour': 'bread flour',
  'wholemeal flour': 'whole wheat flour',
  'wholewheat flour': 'whole wheat flour',
  'strong wholemeal flour': 'whole wheat flour',
  'whole wheat': 'wheat berry',
  'gram flour': 'chickpea flour',
  besan: 'chickpea flour',
  'almond flour': 'ground almond',
  'almond meal': 'ground almond',
  cornflour: 'cornstarch',
  'corn flour': 'cornstarch',
  'corn starch': 'cornstarch',
  starch: 'cornstarch',
  'semolina flour': 'semolina',
  'ground rice': 'rice flour',
  polenta: 'cornmeal',
  'yellow cornmeal': 'cornmeal',
  'white cornmeal': 'cornmeal',
  'yellow masarepa': 'masarepa',
  oat: 'oats',
  'rolled oats': 'oats',
  'porridge oats': 'oats',
  oatmeal: 'oats',
  'ground oats': 'oats',
  'steel cut oats': 'oats',
  'bulgur wheat': 'bulgur',
  'cracked wheat': 'bulgur',
  'pearl barley': 'barley',
  'rye grain': 'rye',
  phyllo: 'phyllo dough',
  'phyllo pastry': 'phyllo dough',
  'phyllo sheet': 'phyllo dough',
  'wonton skin': 'wonton wrapper',
  'rice paper sheet': 'rice paper',
  'rice paper wrapper': 'rice paper',
  // Legumes
  'chick pea': 'chickpea',
  garbanzo: 'chickpea',
  'garbanzo bean': 'chickpea',
  'split red lentil': 'red lentil',
  'masoor dal': 'red lentil',
  'french lentil': 'puy lentil',
  'green red lentil': 'lentil',
  dal: 'lentil',
  dhal: 'lentil',
  'red kidney bean': 'kidney bean',
  'black turtle bean': 'black bean',
  'haricot bean': 'navy bean',
  'white navy bean': 'navy bean',
  'cranberry bean': 'borlotti bean',
  'butter bean': 'lima bean',
  'broad bean': 'fava bean',
  ful: 'fava bean',
  'ful medames': 'fava bean',
  'fool medames': 'fava bean',
  'black eyed pea': 'black-eyed pea',
  'soy bean': 'soybean',
  'soya bean': 'soybean',
  'mixed bean': 'bean',
  // Sugars, sweeteners and baking
  'caster sugar': 'sugar',
  'golden caster sugar': 'sugar',
  'granulated sugar': 'sugar',
  'white sugar': 'sugar',
  'superfine sugar': 'sugar',
  'cane sugar': 'sugar',
  'light brown sugar': 'brown sugar',
  'dark brown sugar': 'brown sugar',
  'soft brown sugar': 'brown sugar',
  'light brown soft sugar': 'brown sugar',
  'dark brown soft sugar': 'brown sugar',
  'light soft brown sugar': 'brown sugar',
  'dark soft brown sugar': 'brown sugar',
  'turbinado sugar': 'demerara sugar',
  'icing sugar': 'powdered sugar',
  'confectioners sugar': 'powdered sugar',
  "confectioners' sugar": 'powdered sugar',
  'coco sugar': 'coconut sugar',
  jaggery: 'palm sugar',
  'sugar syrup': 'simple syrup',
  'clear honey': 'honey',
  'runny honey': 'honey',
  'black treacle': 'molasses',
  treacle: 'molasses',
  'agave nectar': 'agave syrup',
  'plain chocolate': 'dark chocolate',
  'semi-sweet chocolate': 'dark chocolate',
  'bittersweet chocolate': 'dark chocolate',
  'dark chocolate chip': 'chocolate chip',
  'white chocolate chip': 'white chocolate',
  cocoa: 'cocoa powder',
  cacao: 'cocoa powder',
  'cacao powder': 'cocoa powder',
  'instant yeast': 'yeast',
  'fast action yeast': 'yeast',
  'fast-action yeast': 'yeast',
  'active dry yeast': 'yeast',
  'easy bake yeast': 'yeast',
  'gelatin leaf': 'gelatin',
  'leaf gelatin': 'gelatin',
  'gelatin sheet': 'gelatin',
  'powdered gelatin': 'gelatin',
  'pink food coloring': 'food coloring',
  'yellow food coloring': 'food coloring',
  'red food coloring': 'food coloring',
  'vanilla ice cream': 'ice cream',
  // Nuts and seeds
  'cashew nut': 'cashew',
  'pistachio nut': 'pistachio',
  'ground pistachio': 'pistachio',
  'ground walnut': 'walnut',
  'pecan nut': 'pecan',
  'pine kernel': 'pine nut',
  groundnut: 'peanut',
  'white sesame seed': 'sesame seed',
  'black sesame seed': 'sesame seed',
  // Oils and fats
  'extra virgin olive oil': 'olive oil',
  'extra-virgin olive oil': 'olive oil',
  'virgin olive oil': 'olive oil',
  'light olive oil': 'olive oil',
  evoo: 'olive oil',
  'cooking oil': 'oil',
  'neutral oil': 'oil',
  'frying oil': 'oil',
  'high heat cooking oil': 'oil',
  'cooking spray': 'oil',
  'olive oil spray': 'olive oil',
  canola: 'canola oil',
  'rapeseed oil': 'canola oil',
  'groundnut oil': 'peanut oil',
  'ground nut oil': 'peanut oil',
  'vegetable shortening': 'shortening',
  // Sauces, condiments, stocks
  'light soy sauce': 'soy sauce',
  'dark soy sauce': 'soy sauce',
  'soya sauce': 'soy sauce',
  'low sodium soy sauce': 'soy sauce',
  worcestershire: 'worcestershire sauce',
  hotsauce: 'hot sauce',
  tabasco: 'hot sauce',
  'tabasco sauce': 'hot sauce',
  'sriracha sauce': 'sriracha',
  'tomato ketchup': 'ketchup',
  'tahini paste': 'tahini',
  'chili bean paste': 'doubanjiang',
  'miso paste': 'miso',
  'green salsa': 'salsa verde',
  'pico de gallo sauce': 'pico de gallo',
  'thai red curry paste': 'red curry paste',
  'thai green curry paste': 'green curry paste',
  'madras paste': 'madras curry paste',
  'vinaigrette dressing': 'vinaigrette',
  'tamarind paste': 'tamarind',
  'tamarind pulp': 'tamarind',
  'tamarind concentrate': 'tamarind',
  'galangal paste': 'galangal',
  'white vinegar': 'vinegar',
  'distilled vinegar': 'vinegar',
  'vegan white wine vinegar': 'white wine vinegar',
  'cider vinegar': 'apple cider vinegar',
  balsamic: 'balsamic vinegar',
  'rice wine vinegar': 'rice vinegar',
  'seasoned rice vinegar': 'rice vinegar',
  'chicken broth': 'chicken stock',
  'chicken stock cube': 'chicken stock',
  'chicken bouillon': 'chicken stock',
  'chicken bouillon cube': 'chicken stock',
  'chicken bouillon powder': 'chicken stock',
  'chicken stock powder': 'chicken stock',
  'vegetable broth': 'vegetable stock',
  'vegetable stock cube': 'vegetable stock',
  'vegetable bouillon': 'vegetable stock',
  'veg stock': 'vegetable stock',
  'veggie stock': 'vegetable stock',
  'stock cube': 'stock',
  'bouillon cube': 'stock',
  bouillon: 'stock',
  broth: 'stock',
  'light coconut milk': 'coconut milk',
  'shaoxing rice wine': 'shaoxing wine',
  'cooking wine': 'wine',
  'sweet sherry': 'sherry',
  'dark rum': 'rum',
  'white rum': 'rum',
  'dark beer': 'beer',
  cognac: 'brandy',
  'grand marnier': 'orange liqueur',
  'cafe la llave': 'coffee',
  'dill pickle': 'pickle',
  gherkin: 'pickle',
  cornichon: 'pickle',
  'pimento stuffed olive': 'green olive',
  kalamata: 'kalamata olive',
  'white sauerkraut': 'sauerkraut',
  'ice cube': 'ice',
  'sparkling water': 'soda water',
  'fried ripe banana': 'banana',
} as const

/**
 * Canonical names that no synonym or family entry produces but the engine must know: the spec's
 * core vocabulary plus names that contain a descriptor word ("dried apricot") or end in a word the
 * normalizer would otherwise drop ("bay leaf", "custard powder").
 */
export const CORE_CANONICALS: readonly string[] = [
  'chicken',
  'chicken breast',
  'chicken thigh',
  'chicken wing',
  'chicken liver',
  'beef liver',
  'lamb liver',
  'pastirma',
  'rabbit',
  'pigeon',
  'ground beef',
  'beef',
  'steak',
  'ground lamb',
  'lamb',
  'lamb kidney',
  'lamb fat',
  'ground pork',
  'pork',
  'bacon',
  'sausage',
  'ham',
  'turkey ham',
  'chorizo',
  'turkey',
  'duck',
  'goat',
  'veal',
  'oxtail',
  'corned beef',
  'egg',
  'egg yolk',
  'egg white',
  'flax egg',
  'tofu',
  'tempeh',
  'salmon',
  'smoked salmon',
  'tuna',
  'cod',
  'salt cod',
  'white fish',
  'fish',
  'fish stick',
  'shrimp',
  'dried shrimp',
  'shrimp paste',
  'mussel',
  'clam',
  'squid',
  'octopus',
  'anchovy',
  'sardine',
  'haddock',
  'smoked haddock',
  'mackerel',
  'crab',
  'crab stick',
  'lobster',
  'oyster',
  'scallop',
  'milk',
  'milk powder',
  'butter',
  'vegan butter',
  'margarine',
  'cream',
  'heavy cream',
  'clotted cream',
  'sour cream',
  'creme fraiche',
  'yogurt',
  'greek yogurt',
  'frozen yogurt',
  'labneh',
  'buttermilk',
  'evaporated milk',
  'condensed milk',
  'almond milk',
  'oat milk',
  'cheese',
  'cheddar',
  'mozzarella',
  'parmesan',
  'feta',
  'halloumi',
  'ricotta',
  'cream cheese',
  'cottage cheese',
  'mascarpone',
  'paneer',
  'goat cheese',
  'gruyere',
  'ghee',
  'onion',
  'red onion',
  'shallot',
  'green onion',
  'garlic',
  'wild garlic',
  'tomato',
  'cherry tomato',
  'tomato paste',
  'tomato sauce',
  'passata',
  'sun-dried tomato',
  'potato',
  'sweet potato',
  'carrot',
  'celery',
  'celeriac',
  'cucumber',
  'bell pepper',
  'chili',
  'jalapeno',
  'eggplant',
  'zucchini',
  'mushroom',
  'dried mushroom',
  'spinach',
  'lettuce',
  'cabbage',
  'cauliflower',
  'broccoli',
  'green bean',
  'pea',
  'corn',
  'baby corn',
  'creamed corn',
  'okra',
  'leek',
  'pumpkin',
  'pumpkin puree',
  'butternut squash',
  'squash',
  'beet',
  'avocado',
  'kale',
  'fennel',
  'fennel seed',
  'parsnip',
  'turnip',
  'radish',
  'asparagus',
  'artichoke',
  'artichoke heart',
  'jerusalem artichoke',
  'swiss chard',
  'bean sprout',
  'water chestnut',
  'bamboo shoot',
  'mixed vegetable',
  'vegetable',
  'plantain',
  'cassava',
  'cassava flour',
  'taro',
  'yam',
  'breadfruit',
  'ackee',
  'callaloo',
  'lemon',
  'lime',
  'dried lime',
  'orange',
  'apple',
  'banana',
  'pear',
  'peach',
  'apricot',
  'dried apricot',
  'plum',
  'mango',
  'pineapple',
  'pineapple juice',
  'grapefruit',
  'pomegranate',
  'pomegranate molasses',
  'fig',
  'dried fig',
  'date',
  'date molasses',
  'prune',
  'raisin',
  'currant',
  'dried fruit',
  'cherry',
  'dried cherry',
  'ground cherry',
  'glace cherry',
  'cranberry',
  'dried cranberry',
  'strawberry',
  'raspberry',
  'blueberry',
  'blackberry',
  'mixed berry',
  'rhubarb',
  'grape',
  'watermelon',
  'melon',
  'guava',
  'kiwi',
  'coconut',
  'molokhia',
  'vine leaf',
  'bay leaf',
  'curry leaf',
  'lime leaf',
  'banana leaf',
  'pandan leaf',
  'coriander',
  'ground coriander',
  'parsley',
  'mint',
  'dill',
  'basil',
  'oregano',
  'thyme',
  'rosemary',
  'sage',
  'tarragon',
  'chive',
  'marjoram',
  'savory',
  'lemongrass',
  'galangal',
  'cumin',
  'paprika',
  'smoked paprika',
  'turmeric',
  'cinnamon',
  'cardamom',
  'clove',
  'nutmeg',
  'ginger',
  'ground ginger',
  'garam masala',
  'curry powder',
  'sumac',
  "za'atar",
  'allspice',
  'saffron',
  'chili powder',
  'chili flakes',
  'cayenne pepper',
  'white pepper',
  'sichuan pepper',
  'black pepper',
  'star anise',
  'five spice powder',
  'mixed spice',
  'ras el hanout',
  'baharat',
  'caraway seed',
  'mustard seed',
  'poppy seed',
  'nigella seed',
  'fenugreek',
  'mahleb',
  'mastic',
  'salt',
  'celery salt',
  'onion salt',
  'garlic powder',
  'onion powder',
  'mustard',
  'mustard powder',
  'sesame seed',
  'tahini',
  'rice',
  'basmati rice',
  'wild rice',
  'pasta',
  'spaghetti',
  'macaroni',
  'noodle',
  'gnocchi',
  'lentil',
  'red lentil',
  'split pea',
  'chickpea',
  'chickpea flour',
  'kidney bean',
  'black bean',
  'fava bean',
  'bean',
  'baked bean',
  'refried bean',
  'fermented black bean',
  'mung bean',
  'bulgur',
  'couscous',
  'freekeh',
  'quinoa',
  'buckwheat',
  'barley',
  'oats',
  'semolina',
  'cornmeal',
  'masa harina',
  'bread',
  'pita',
  'flatbread',
  'tortilla',
  'taco shell',
  'english muffin',
  'breadcrumb',
  'flour',
  'self-raising flour',
  'rice flour',
  'rye flour',
  'buckwheat flour',
  'cornstarch',
  'potato starch',
  'tapioca',
  'sugar',
  'brown sugar',
  'powdered sugar',
  'vanilla sugar',
  'honey',
  'maple syrup',
  'golden syrup',
  'molasses',
  'chocolate',
  'white chocolate',
  'hot chocolate',
  'cocoa powder',
  'olive oil',
  'vegetable oil',
  'oil',
  'sesame oil',
  'truffle oil',
  'lard',
  'suet',
  'shortening',
  'goose fat',
  'vinegar',
  'soy sauce',
  'tamari',
  'fish sauce',
  'oyster sauce',
  'hoisin sauce',
  'worcestershire sauce',
  'hot sauce',
  'chili sauce',
  'sweet chili sauce',
  'barbecue sauce',
  'ketchup',
  'mayonnaise',
  'pesto',
  'gochujang',
  'doubanjiang',
  'miso',
  'salsa',
  'hummus',
  'chicken stock',
  'vegetable stock',
  'beef stock',
  'stock',
  'coconut milk',
  'coconut cream',
  'yeast',
  'baking powder',
  'baking soda',
  'cream of tartar',
  'gelatin',
  'custard powder',
  'water',
  'ice',
  'soda water',
  'almond',
  'almond extract',
  'vanilla',
  'walnut',
  'pistachio',
  'pine nut',
  'peanut',
  'peanut butter',
  'hazelnut',
  'pecan',
  'chestnut',
  'cashew',
  'wine',
  'rice wine',
  'mirin',
  'sake',
  'sherry',
  'brandy',
  'rum',
  'beer',
  'cider',
  'puff pastry',
  'shortcrust pastry',
  'phyllo dough',
  'egg roll wrapper',
  'wonton wrapper',
  'rice paper',
  'olive',
  'caper',
  'pickle',
  'sauerkraut',
  'jam',
  'ice cream',
  'custard',
  'mixed herb',
  'italian seasoning',
  'herbes de provence',
  'bouquet garni',
  'seasoning',
  'sazon',
  'harissa',
  'tamarind',
  'rose water',
  'orange blossom water',
  'knafeh',
  'falafel',
  'food coloring',
]

/** Every name the engine treats as canonical: the core list plus everything the tables produce. */
export const CANONICAL_NAMES: ReadonlySet<string> = new Set([
  ...CORE_CANONICALS,
  ...Object.values(SYNONYMS),
  ...Object.keys(FAMILIES),
  ...Object.values(FAMILIES),
  ...STAPLES,
])

export function lookupSynonym(phrase: string): string | undefined {
  const key = phrase.trim().toLowerCase().replace(/\s+/g, ' ')
  return Object.hasOwn(SYNONYMS, key) ? SYNONYMS[key] : undefined
}
