import { z } from 'zod'
import { CanonicalNameSchema } from '@/types/recipe'
import { PORTION_KEYS } from './fdc'

/**
 * The nutrition data files, keyed by canonical ingredient name:
 * - data/nutrition/fdc-mapping.json (reviewed by a person): which USDA FoodData Central food
 *   stands for each ingredient, or why none does.
 * - data/nutrition/foods.json (generated by `pnpm seed:nutrition`): that food's values per
 *   100 g and gram weights, exactly as USDA publishes them.
 */

const FoodRefSchema = z.strictObject({
  fdcId: z.number().int().positive(),
  /** USDA's description, so a reviewer sees what the id means. */
  description: z.string().min(1),
})

/** Lines naming another form use that form's food ("1 can tomatoes", "desiccated coconut"). */
export const VARIANTS = ['canned', 'dried'] as const
export type Variant = (typeof VARIANTS)[number]

const MappedSchema = FoodRefSchema.extend({
  /** Why this food was chosen when it is not the obvious one, and why any weight is overridden. */
  note: z.string().trim().min(1).optional(),
  /**
   * Gram weights to add (from another USDA food or a standard definition) or to remove (null:
   * USDA's weight does not fit our recipes, e.g. a US breakfast link for British sausages).
   */
  portions: z.partialRecord(z.enum(PORTION_KEYS), z.number().positive().nullable()).optional(),
  variants: z.partialRecord(z.enum(VARIANTS), FoodRefSchema).optional(),
}).refine((entry) => entry.portions === undefined || entry.note !== undefined, {
  message: 'weight overrides need a note saying where the weight comes from',
})

const UnmappedSchema = z.strictObject({
  fdcId: z.null(),
  /** Why no USDA food fits. */
  reason: z.string().trim().min(1),
  /**
   * Only ever used in small amounts (spice blends, flavourings): a teaspoon of it is left out
   * as a small amount instead of making the whole recipe's nutrition unavailable.
   */
  minor: z.literal(true).optional(),
})

export const FdcMappingSchema = z.object({
  version: z.literal(1),
  foods: z.record(CanonicalNameSchema, z.union([MappedSchema, UnmappedSchema])),
})
export type FdcMapping = z.infer<typeof FdcMappingSchema>

const MacrosSchema = z.object({
  kcal: z.number().nonnegative(),
  proteinG: z.number().nonnegative(),
  fatG: z.number().nonnegative(),
  carbsG: z.number().nonnegative(),
  fiberG: z.number().nonnegative().optional(),
})

const FoodValuesSchema = z.object({
  fdcId: z.number().int().positive(),
  description: z.string().min(1),
  dataType: z.string().min(1),
  /** USDA food category, e.g. "Spices and Herbs" (decides what counts as a small amount). */
  category: z.string().min(1).optional(),
  per100g: MacrosSchema,
  portions: z.partialRecord(z.enum(PORTION_KEYS), z.number().positive()),
})
export type FoodValues = z.infer<typeof FoodValuesSchema>

export const NutritionFoodSchema = FoodValuesSchema.extend({
  variants: z.partialRecord(z.enum(VARIANTS), FoodValuesSchema).optional(),
})
export type NutritionFood = z.infer<typeof NutritionFoodSchema>

export const NutritionFoodsSchema = z.object({
  version: z.literal(1),
  source: z.literal('USDA FoodData Central'),
  foods: z.record(CanonicalNameSchema, NutritionFoodSchema),
  /** Ingredients with no USDA food that are only used in small amounts (mapping: minor). */
  minorWithoutFood: z.array(CanonicalNameSchema),
})
export type NutritionFoods = z.infer<typeof NutritionFoodsSchema>
