/**
 * The Arabic display names from data/i18n/ingredients.ar.json that the hand-written alias table
 * does not already resolve to their own ingredient. Typing exactly what the app shows must find
 * that ingredient (a chip, the shopping list and the have/need panel all use these names).
 * Regenerate after editing the display names; consistency.test.ts checks the round trip.
 */
export const ARABIC_DISPLAY_ALIASES = {
  ackee: ['أكي'],
  'acorn squash': ['قرع بلوطي'],
  'almond extract': ['خلاصة اللوز'],
  'ancho chili': ['فلفل أنشو'],
  'apricot jam': ['مربى مشمش'],
  'arborio rice': ['أرز أربوريو'],
  'baby corn': ['ذرة صغيرة'],
  baguette: ['خبز باجيت'],
  'baked bean': ['فاصوليا بيضاء بالصلصة'],
  'bamboo shoot': ['براعم البامبو'],
  'banana leaf': ['ورق موز'],
  barramundi: ['سمك باراموندي'],
  bean: ['حبوب فاصوليا'],
  'bean sprout': ['براعم فاصوليا'],
  beer: ['بيرة'],
  "bird's eye chili": ['فلفل حار تايلاندي'],
  'black lentil': ['عدس أسود'],
  'blackcurrant jam': ['مربى كشمش أسود'],
  'blue cheese': ['جبنة زرقاء'],
  'borlotti bean': ['فاصوليا بورلوتي'],
  'bouquet garni': ['باقة أعشاب'],
  brandy: ['براندي'],
  'bread flour': ['دقيق خبز'],
  'bread roll': ['خبز رول'],
  breadfruit: ['فاكهة الخبز'],
  brie: ['جبنة بري'],
  brisket: ['صدر بقري'],
  buckwheat: ['حنطة سوداء'],
  'buckwheat flour': ['دقيق الحنطة السوداء'],
  bun: ['خبز برجر'],
  'cajun seasoning': ['بهارات كاجن'],
  callaloo: ['كالالو'],
  'cannellini bean': ['فاصوليا كانيليني'],
  cassava: ['كسافا'],
  'cassava flour': ['دقيق كسافا'],
  'celery salt': ['ملح كرفس'],
  'chestnut mushroom': ['مشروم بني'],
  'chicken leg': ['ورك دجاج كامل'],
  'chili sauce': ['صلصة تشيلي'],
  'chinese sesame sauce': ['صوص سمسم صيني'],
  'chocolate chip': ['حبيبات شوكولاتة'],
  ciabatta: ['خبز تشاباتا'],
  cider: ['سيدر تفاح'],
  clam: ['جندوفلي'],
  'clotted cream': ['قشطة إنجليزية'],
  'coconut sugar': ['سكر جوز الهند'],
  'colby jack': ['جبنة كولبي جاك'],
  'cooking apple': ['تفاح للطبخ'],
  'coriander seed': ['بذور الكزبرة'],
  'corn tortilla': ['تورتيلا ذرة'],
  'crab stick': ['كراب ستيك'],
  'creamed corn': ['ذرة بالكريمة'],
  'curry leaf': ['ورق الكاري'],
  custard: ['كاسترد'],
  daikon: ['فجل أبيض'],
  'demerara sugar': ['سكر ديميرارا'],
  'dijon mustard': ['مستردة ديجون'],
  doubanjiang: ['معجون فول حار'],
  'dried cherry': ['كرز مجفف'],
  'dried cranberry': ['توت بري مجفف'],
  'dried shrimp': ['جمبري مجفف'],
  'duck breast': ['صدر بط'],
  'duck leg': ['فخذ بط'],
  'duck sauce': ['صوص البط'],
  'egg noodle': ['نودلز بالبيض'],
  'egg pasta': ['مكرونة بالبيض'],
  'egg roll wrapper': ['عجينة سبرينج رول'],
  emmental: ['جبنة إيمنتال'],
  'enchilada sauce': ['صوص إنشيلادا'],
  'english muffin': ['مافن إنجليزي'],
  'english mustard': ['مستردة إنجليزية'],
  'fajita seasoning': ['بهارات فاهيتا'],
  farfalle: ['مكرونة فراشة'],
  'fermented black bean': ['فول صويا أسود مخمر'],
  fettuccine: ['مكرونة فيتوتشيني'],
  'fish stick': ['أصابع سمك'],
  'five spice powder': ['بهارات صينية خماسية'],
  'flank steak': ['ستيك فلانك'],
  flatbread: ['خبز مسطح'],
  'flax egg': ['بيضة بذر الكتان'],
  'fresh pasta': ['مكرونة طازجة'],
  'fromage frais': ['فروماج فريه'],
  'frozen yogurt': ['زبادي مجمد'],
  fusilli: ['مكرونة فوسيلي'],
  galangal: ['خولنجان'],
  'glace cherry': ['كرز مسكر'],
  'glass noodle': ['نودلز زجاجية'],
  'glutinous rice': ['أرز لزج'],
  gnocchi: ['نيوكي'],
  goat: ['لحم ماعز'],
  gochujang: ['جوتشوجانج'],
  'golden syrup': ['جولدن سيرب'],
  'goose fat': ['دهن إوز'],
  gorgonzola: ['جبنة جورجونزولا'],
  'grapeseed oil': ['زيت بذور العنب'],
  'great northern bean': ['فاصوليا جريت نورثرن'],
  'green papaya': ['بابايا خضراء'],
  'ground almond': ['لوز مطحون'],
  'ground cherry': ['حرنكش'],
  'ground turkey': ['ديك رومي مفروم'],
  'ground veal': ['لحم بتلو مفروم'],
  habanero: ['فلفل هابانيرو'],
  hake: ['سمك نازلي'],
  'half-and-half': ['خليط حليب وكريمة'],
  'herbes de provence': ['أعشاب بروفانس'],
  'hoisin sauce': ['صوص هويسين'],
  horseradish: ['فجل حار'],
  'hot chocolate': ['شوكولاتة ساخنة'],
  'iceberg lettuce': ['خس آيسبرج'],
  'italian sausage': ['سجق إيطالي'],
  'jerusalem artichoke': ['طرطوفة'],
  kabanos: ['سجق كابانوس'],
  'kalamata olive': ['زيتون كالاماتا'],
  kielbasa: ['سجق كيلباسا'],
  'lamb fat': ['دهن خروف'],
  'lamb kidney': ['كلاوي ضاني'],
  'lamb stock': ['مرقة خروف'],
  lard: ['دهن خنزير'],
  'lima bean': ['فاصوليا ليما'],
  'lime leaf': ['ورق ليمون'],
  linguine: ['مكرونة لينجويني'],
  'liquid cheese': ['جبنة سائلة'],
  'little gem lettuce': ['خس ليتل جيم'],
  lobster: ['استاكوزا'],
  longan: ['لونجان'],
  malai: ['قشطة هندية'],
  'malt vinegar': ['خل شعير'],
  manchego: ['جبنة مانشيجو'],
  'masa harina': ['دقيق ماسا'],
  merguez: ['سجق مرقاز'],
  'mexican cheese': ['جبنة مكسيكية'],
  mincemeat: ['حشوة فواكه مجففة'],
  mirin: ['ميرين'],
  miso: ['معجون ميسو'],
  'mixed grain': ['حبوب مشكلة'],
  'mixed seafood': ['مأكولات بحرية مشكلة'],
  'mixed spice': ['بهارات الكيك'],
  monkfish: ['سمك الراهب'],
  'monterey jack': ['جبنة مونتيري جاك'],
  'muscovado sugar': ['سكر موسكوفادو'],
  'mustard powder': ['خردل بودرة'],
  mutton: ['لحم ضاني كبير'],
  naan: ['خبز نان'],
  'navy bean': ['فاصوليا بيضاء صغيرة'],
  octopus: ['أخطبوط'],
  'onion salt': ['ملح بصل'],
  'oreo cream biscuit': ['بسكويت أوريو'],
  oxtail: ['ذيل بقري'],
  oyster: ['محار'],
  'oyster mushroom': ['مشروم المحار'],
  paccheri: ['مكرونة باكيري'],
  'paella rice': ['أرز باييا'],
  'palm sugar': ['سكر النخيل'],
  pancetta: ['بانشيتا'],
  'pandan leaf': ['ورق باندان'],
  paneer: ['جبنة بانير'],
  panko: ['بقسماط بانكو'],
  passata: ['بوريه طماطم'],
  'peanut oil': ['زيت فول سوداني'],
  'pearl onion': ['بصل لؤلؤي'],
  pecorino: ['جبنة بيكورينو'],
  'pickle juice': ['ماء المخلل'],
  'pineapple juice': ['عصير أناناس'],
  'pinto bean': ['فاصوليا بينتو'],
  plantain: ['موز الطبخ'],
  'plum jam': ['مربى برقوق'],
  pollock: ['سمك بولوك'],
  porcini: ['مشروم بورتشيني'],
  'pork belly': ['بطن خنزير'],
  'pork chop': ['ريش خنزير'],
  'pork knuckle': ['ساق خنزير'],
  'pork loin': ['ظهر خنزير'],
  'pork rib': ['ضلوع خنزير'],
  'pork shoulder': ['كتف خنزير'],
  'pork tenderloin': ['فيليه خنزير'],
  'portobello mushroom': ['مشروم بورتوبيلو'],
  'potato starch': ['نشا بطاطس'],
  prosciutto: ['بروشوتو'],
  'pudding rice': ['أرز للحلويات'],
  'pumpkin puree': ['قرع عسلي مهروس'],
  'puy lentil': ['عدس بوي'],
  'ramen noodle': ['نودلز رامن'],
  'raspberry jam': ['مربى راسبيري'],
  'red curry paste': ['معجون كاري أحمر'],
  'red pepper paste': ['معجون فلفل أحمر'],
  'red wine': ['نبيذ أحمر'],
  'red wine vinegar': ['خل نبيذ أحمر'],
  'refried bean': ['فاصوليا مهروسة'],
  rhubarb: ['راوند'],
  'rice noodle': ['نودلز أرز'],
  'rice paper': ['ورق أرز'],
  'rice vinegar': ['خل أرز'],
  'rice wine': ['نبيذ أرز'],
  rigatoni: ['مكرونة ريجاتوني'],
  'roasted red pepper': ['فلفل أحمر مشوي'],
  'romaine lettuce': ['خس روماني'],
  rum: ['رم'],
  'rump steak': ['ستيك رامب'],
  rutabaga: ['لفت سويدي'],
  'rye bread': ['خبز الجاودار'],
  'rye flour': ['دقيق جاودار'],
  sake: ['ساكي'],
  salsa: ['صوص سالسا'],
  'salsa verde': ['سالسا خضراء'],
  'salt cod': ['سمك قد مملح'],
  sauerkraut: ['مخلل كرنب'],
  savory: ['صعتر صيفي'],
  'savoy cabbage': ['كرنب سافوي'],
  sazon: ['بهارات سازون'],
  scallop: ['إسكالوب بحري'],
  'scotch bonnet': ['فلفل سكوتش بونيت'],
  seasoning: ['تتبيلة'],
  'serrano chili': ['فلفل سيرانو'],
  'shaoxing wine': ['نبيذ شاوشينغ'],
  sherry: ['نبيذ شيري'],
  'sherry vinegar': ['خل شيري'],
  'shiitake mushroom': ['مشروم شيتاكي'],
  'short grain rice': ['أرز قصير الحبة'],
  'short rib': ['ضلوع بقري'],
  'shortcrust pastry': ['عجينة تارت'],
  'shrimp paste': ['معجون جمبري'],
  'sichuan pepper': ['فلفل سيشوان'],
  'silken tofu': ['توفو حريري'],
  'sirloin steak': ['ستيك سيرلوين'],
  'skirt steak': ['ستيك سكيرت'],
  'smoked haddock': ['سمك حدوق مدخن'],
  snapper: ['سمك النهاش'],
  'snow pea': ['بسلة صيني'],
  soba: ['نودلز سوبا'],
  'soda water': ['مياه صودا'],
  'sourdough bread': ['خبز ساوردو'],
  squash: ['قرع شتوي'],
  'sticky rice flour': ['دقيق أرز لزج'],
  stilton: ['جبنة ستيلتون'],
  stout: ['بيرة ستاوت'],
  'strawberry jam': ['مربى فراولة'],
  suet: ['شحم بقري'],
  'sugar snap pea': ['بسلة سكرية'],
  'sushi rice': ['أرز سوشي'],
  'swiss cheese': ['جبنة سويسرية'],
  'taco shell': ['خبز تاكو'],
  tagliatelle: ['مكرونة تالياتيلي'],
  tamari: ['صوص تاماري'],
  tapioca: ['تابيوكا'],
  tempeh: ['تمبيه'],
  'toor dal': ['تور دال'],
  trout: ['سمك التراوت'],
  'truffle oil': ['زيت ترافل'],
  'turkey breast': ['صدر ديك رومي'],
  'turkey ham': ['هام ديك رومي'],
  udon: ['نودلز أودون'],
  'vanilla bean': ['عود فانيليا'],
  'vanilla bean paste': ['معجون فانيليا'],
  'vanilla sugar': ['سكر فانيليا'],
  vasterbottensost: ['جبنة فاستربوتن'],
  'vegan butter': ['زبدة فيجان'],
  vegetable: ['خضار'],
  vinaigrette: ['صوص فينيجريت'],
  'water chestnut': ['كستناء الماء'],
  'white wine': ['نبيذ أبيض'],
  'white wine vinegar': ['خل نبيذ أبيض'],
  'wholegrain mustard': ['مستردة بالحبوب'],
  'wild garlic': ['ثوم بري'],
  'wild mushroom': ['مشروم بري'],
  'wild rice': ['أرز بري'],
  wine: ['نبيذ'],
  'wonton wrapper': ['رقائق ونتون'],
  'wood ear mushroom': ['مشروم أذن الخشب'],
  yam: ['يام'],
} as const satisfies Readonly<Record<string, readonly string[]>>
