/**
 * Preparation, size, state and quality words that never change what you buy. Stripped after the
 * first synonym pass, so "minced beef" reaches the synonym table before "minced" is dropped, and
 * never from inside a canonical name or a protected phrase ("hot sauce", "whole wheat flour").
 */
export const DESCRIPTOR_WORDS: ReadonlySet<string> = new Set([
  // Spec list
  'fresh',
  'chopped',
  'diced',
  'minced',
  'sliced',
  'large',
  'small',
  'ripe',
  'boneless',
  'skinless',
  'bone-in',
  'skin-on',
  'skin-off',
  'organic',
  'optional',
  // Size and quantity colour
  'medium',
  'big',
  'little',
  'lg',
  'lrg',
  'med',
  'sm',
  'extra',
  'extra-large',
  'jumbo',
  'baby',
  'mini',
  'thick',
  'thin',
  'whole',
  'lean',
  'heaped',
  'heaping',
  'level',
  'rounded',
  'scant',
  'generous',
  'good',
  'quality',
  'good-quality',
  'best',
  'pure',
  'mild',
  'mature',
  'fine',
  'coarse',
  'flaky',
  // How it is cut or prepared
  'finely',
  'roughly',
  'coarsely',
  'thinly',
  'thickly',
  'lightly',
  'freshly',
  'squeezed',
  'peeled',
  'unpeeled',
  'deseeded',
  'seeded',
  'cored',
  'trimmed',
  'crushed',
  'grated',
  'shredded',
  'beaten',
  'whisked',
  'softened',
  'melted',
  'cubed',
  'halved',
  'quartered',
  'julienned',
  'torn',
  'cracked',
  'slivered',
  'flaked',
  'mashed',
  'pureed',
  'rinsed',
  'drained',
  'washed',
  'scrubbed',
  'soaked',
  'thawed',
  'defrosted',
  'pitted',
  'stoned',
  'shelled',
  'skinned',
  'deveined',
  'blanched',
  'toasted',
  'roasted',
  'fried',
  'steamed',
  'boiled',
  'cooked',
  'uncooked',
  'raw',
  'leftover',
  'stale',
  'filled',
  'cut',
  'very',
  'sized',
  'shaved',
  'pounded',
  'bashed',
  'crumbled',
  'dry-cured',
  'separated',
  'seperated',
  // Temperature
  'cold',
  'chilled',
  'iced',
  'warm',
  'lukewarm',
  'hot',
  'boiling',
  // Storage and sourcing
  'frozen',
  'canned',
  'tinned',
  'jarred',
  'dried',
  'dry',
  'desiccated',
  'unsalted',
  'unsweetened',
  'unwaxed',
  'unflavored',
  'unflavoured',
  'free-range',
  'semi-skimmed',
  'skimmed',
  'skim',
  'part-skim',
  'nonfat',
  'non-fat',
  'low-sodium',
  'full-fat',
  'low-fat',
  'reduced-fat',
  'fat-free',
  'homemade',
  'store-bought',
  'shop-bought',
  'ready-made',
  'ready-rolled',
])

/** Multi-word descriptors, removed before single words so "room temperature" goes as a unit. */
export const DESCRIPTOR_PHRASES: readonly (readonly string[])[] = [
  ['at', 'room', 'temperature'],
  ['room', 'temperature'],
  ['to', 'taste'],
  ['free', 'range'],
  ['full', 'fat'],
  ['low', 'fat'],
  ['reduced', 'fat'],
  ['fat', 'free'],
  ['semi', 'skimmed'],
  ['good', 'quality'],
  ['store', 'bought'],
  ['shop', 'bought'],
  ['ready', 'made'],
  ['ready', 'rolled'],
  ['bite', 'sized'],
  ['bone', 'in'],
  ['skin', 'on'],
  ['skin', 'off'],
  ['part', 'skim'],
  ['non', 'fat'],
  ['low', 'sodium'],
  ['juice', 'of'],
  ['zest', 'of'],
]

/**
 * Phrases a descriptor word belongs to, kept whole so the synonym table can map them ("lean minced
 * beef" → "minced beef" → ground beef, never "beef"). Canonical names are protected automatically.
 */
export const PROTECTED_PHRASES: ReadonlySet<string> = new Set([
  'minced beef',
  'minced lamb',
  'minced pork',
  'minced turkey',
  'minced chicken',
  'minced meat',
  'minced steak',
  'crushed red pepper',
  'crushed chili',
  'hot pepper',
  'hot sauce',
  'hot dog',
  'whole wheat',
  'whole grain',
  'dry mustard',
  'baby plum tomato',
  'baby gem lettuce',
  'baby back rib',
  'roasted pepper',
  'dry milk',
  'dried milk',
  'little gem',
  'baby gem',
  'jelly baby',
])

/** Words that open a trailing clause: "oil for frying", "tuna in brine", "butter, plus extra". */
export const CLAUSE_STARTERS: ReadonlySet<string> = new Set([
  'for',
  'with',
  'plus',
  'if',
  'as',
  'such',
  'in',
  'eg',
])

/** After "to", these verbs start a clause ("lemon wedges to serve", "salt to taste"). */
export const TO_CLAUSE_VERBS: ReadonlySet<string> = new Set([
  'serve',
  'taste',
  'garnish',
  'decorate',
  'finish',
  'dust',
  'drizzle',
  'sprinkle',
  'top',
  'glaze',
  'coat',
  'brush',
  'grease',
  'fry',
  'cook',
  'season',
])

/**
 * What an ingredient is for. TheMealDB writes these as the measure ("Garnish", "To serve",
 * "For frying", "As required"), so they can open a "measure + name" line and are dropped there.
 */
export const PURPOSE_WORDS: ReadonlySet<string> = new Set([
  'garnish',
  'garnishing',
  'topping',
  'dusting',
  'greasing',
  'brushing',
  'glazing',
  'decoration',
  'decorating',
  'serving',
  'frying',
  'drizzling',
])

/** After a leading "to", "for" or "as", these words finish the purpose ("as required", "to serve"). */
export const PURPOSE_FOLLOWERS: ReadonlySet<string> = new Set([
  ...PURPOSE_WORDS,
  ...TO_CLAUSE_VERBS,
  'required',
  'needed',
  'desired',
])

/**
 * Phrases that open the text before a quantity ("juice of 1 lemon", "zest and juice of 2 limes").
 * They are stripped with the leading quantities, because the amount sits between them and the name.
 */
export const LEADING_PHRASES: readonly (readonly string[])[] = [
  ['finely', 'grated', 'zest', 'and', 'juice', 'of'],
  ['grated', 'zest', 'and', 'juice', 'of'],
  ['zest', 'and', 'juice', 'of'],
  ['juice', 'and', 'zest', 'of'],
  ['finely', 'grated', 'zest', 'of'],
  ['grated', 'zest', 'of'],
  ['the', 'juice', 'of'],
  ['the', 'zest', 'of'],
  ['juice', 'of'],
  ['zest', 'of'],
  ['up', 'to'],
  ['plus', 'extra'],
  ['plus', 'more'],
]
