/**
 * Curated keyword lists behind the diet classifier.
 *
 * Every phrase is written in the classifier's match form: lowercase ASCII words separated by single
 * spaces (no hyphens or apostrophes — "goat's cheese" is written "goats cheese", "gluten-free" is
 * "gluten free"). Phrases match on word boundaries and the last word tolerates a plural, so 'egg'
 * also matches "eggs" and 'anchovy' matches "anchovies", but 'egg' never matches "eggplant".
 *
 * The lists are deliberately conservative: when a processed product often contains an ingredient
 * (stock cubes and wheat, Thai curry paste and shrimp, pesto and parmesan) it is listed, because
 * under-claiming "vegan" or "gluten-free" is safe and over-claiming is not.
 */

/** Ingredient categories the diet rules are built from. */
export const DIET_CATEGORIES = ['meat', 'fish', 'dairy', 'egg', 'animal', 'gluten'] as const
export type DietCategory = (typeof DIET_CATEGORIES)[number]

/** Non-empty, so every list compiles to a real pattern. */
export type PhraseList = readonly [string, ...string[]]

export interface CategoryKeywords {
  /** Phrases that put an ingredient in the category. */
  readonly keywords: PhraseList
  /** Phrases blanked out before keywords are matched ('peanut butter' is not butter). */
  readonly exceptions: PhraseList
  /** Modifiers that clear the whole ingredient of the category ('vegan cheese', 'tamari'). */
  readonly neutralizers: PhraseList
}

/** Meat, poultry, game, offal, animal fats, meat stocks and gelatin (gelatin counts as meat). */
const MEAT = {
  keywords: [
    // Red meat, game and cuts that are only ever meat.
    'beef',
    'beefsteak',
    'veal',
    'pork',
    'pig',
    'piglet',
    'lamb',
    'mutton',
    'hogget',
    'goat',
    'venison',
    'deer',
    'elk',
    'moose',
    'bison',
    'boar',
    'rabbit',
    'hare',
    'kangaroo',
    'horse',
    'camel',
    'ox',
    'oxtail',
    'steak',
    'sirloin',
    'ribeye',
    'rib eye',
    'tenderloin',
    'filet mignon',
    'brisket',
    'rump',
    'chuck',
    'flank',
    'silverside',
    'topside',
    'shank',
    'short rib',
    'spare rib',
    'sparerib',
    'back rib',
    'osso buco',
    // Poultry, game birds and other animals.
    'chicken',
    'poussin',
    'capon',
    'cornish hen',
    'turkey',
    'duck',
    'duckling',
    'goose',
    'quail',
    'pheasant',
    'partridge',
    'grouse',
    'pigeon',
    'squab',
    'guinea fowl',
    'poultry',
    'wing',
    'drumstick',
    'frog',
    'snail',
    'escargot',
    'alligator',
    'crocodile',
    // Cured and processed meat.
    'bacon',
    'pancetta',
    'guanciale',
    'lardon',
    'prosciutto',
    'ham',
    'gammon',
    'speck',
    'coppa',
    'bresaola',
    'jamon',
    'pastrami',
    'salami',
    'pepperoni',
    'chorizo',
    'sausage',
    'chipolata',
    'bratwurst',
    'frankfurter',
    'wiener',
    'hot dog',
    'kielbasa',
    'kabanos',
    'merguez',
    'morcilla',
    'mortadella',
    'nduja',
    'soppressata',
    'sucuk',
    'sujuk',
    'soujouk',
    'pastirma',
    'basturma',
    'bastirma',
    'jerky',
    'biltong',
    'luncheon meat',
    'meatball',
    'meatloaf',
    'burger',
    'hamburger',
    'black pudding',
    'white pudding',
    'blood sausage',
    'haggis',
    'pate',
    'foie gras',
    'liverwurst',
    'chicharron',
    'crackling',
    'andouille',
    'linguica',
    'sobrasada',
    'lardo',
    'char siu',
    'lap cheong',
    'spam',
    // Meat dishes sold or listed as an ingredient.
    'kofta',
    'kibbeh',
    'shawarma',
    'gyro',
    'doner',
    // Suet-based products.
    'mincemeat',
    'christmas pudding',
    // Offal and animal fats.
    'liver',
    'kidney',
    'tripe',
    'offal',
    'giblet',
    'gizzard',
    'sweetbread',
    'trotter',
    'bone marrow',
    'marrowbone',
    'marrow bone',
    'bone broth',
    'lard',
    'dripping',
    'tallow',
    'suet',
    'schmaltz',
    // Traditionally fried in lard.
    'refried bean',
    // Generic meat words, including UK "mince".
    'meat',
    'mince',
    // Stocks of unknown origin are assumed to be meat-based.
    'stock',
    'broth',
    'bouillon',
    'consomme',
    'gravy',
    'demi glace',
    'oxo',
    'bovril',
    // Gelatin and what is set with it.
    'gelatin',
    'gelatine',
    'aspic',
    'marshmallow',
    'jello',
    'jelly cube',
    'jelly crystal',
    'jelly baby',
    'gummy',
    'xo sauce',
  ],
  exceptions: [
    // Plants and fungi with animal names.
    'kidney bean',
    'pigeon pea',
    'horse gram',
    'chicken of the woods',
    'lambs lettuce',
    'lamb lettuce',
    'lambs quarters',
    'beef tomato',
    'beefsteak tomato',
    'beefsteak mushroom',
    'turkey berry',
    'wing bean',
    'moringa drumstick',
    'drumstick vegetable',
    'drumstick leaf',
    'duck sauce',
    // Animal products that are not meat.
    'duck egg',
    'quail egg',
    'goose egg',
    'goats cheese',
    'goat cheese',
    'goats milk',
    'goat milk',
    'goats yogurt',
    'goat yogurt',
    'goats butter',
    'goat butter',
    // Fish and seafood that the meat words would otherwise catch.
    'bombay duck',
    'horse mackerel',
    'cod liver',
    'monkfish liver',
    'crab meat',
    'lobster meat',
    'clam meat',
    'shrimp meat',
    'prawn meat',
    'tuna steak',
    'salmon steak',
    'swordfish steak',
    'cod steak',
    'halibut steak',
    'fish stock',
    'fish broth',
    'seafood stock',
    'seafood broth',
    'shrimp stock',
    'prawn stock',
    'lobster stock',
    'crab stock',
    'clam broth',
    // Breads and spice mixes named after what goes in them.
    'hamburger bun',
    'burger bun',
    'hot dog bun',
    'hot dog roll',
    'shawarma bread',
    'gyro bread',
    'shawarma spice',
    'shawarma seasoning',
    'gyro seasoning',
    // Vegetable versions of meat words.
    'coconut meat',
    'soy mince',
    'soya mince',
    'quorn mince',
    'bean burger',
    'mushroom burger',
    'mock duck',
    'mock meat',
    'meat substitute',
    'meat alternative',
    'cauliflower steak',
    'mushroom steak',
    'tofu steak',
    'cabbage steak',
    'celeriac steak',
    'vegetable stock',
    'vegetable broth',
    'vegetable bouillon',
    'veg stock',
    'mushroom stock',
    'mushroom broth',
    'vegetable gravy',
    'mushroom gravy',
    'court bouillon',
    'vegetable suet',
    'gelatin free',
    'gelatine free',
    // Labelled vegetarian versions that are plain plant products, not meat stand-ins.
    'vegetarian stock',
    'veggie stock',
    'vegetarian broth',
    'veggie broth',
    'vegetarian bouillon',
    'veggie bouillon',
    'vegetarian gravy',
    'veggie gravy',
    'vegetarian refried bean',
    // French pastry doughs ("pate brisee") are not pâté.
    'pate brisee',
    'pate sucree',
    'pate feuilletee',
    'pate a choux',
  ],
  neutralizers: ['vegetarian', 'vegan', 'veggie', 'meat free', 'meatless', 'plant based'],
} as const satisfies CategoryKeywords

/** Fish, shellfish and the sauces, pastes and stocks made from them. */
const FISH = {
  keywords: [
    'fish',
    'seafood',
    'shellfish',
    // Fish.
    'anchovy',
    'sardine',
    'pilchard',
    'sprat',
    'herring',
    'kipper',
    'bloater',
    'mackerel',
    'salmon',
    'trout',
    'tuna',
    'bonito',
    'cod',
    'codfish',
    'saltfish',
    'stockfish',
    'bacalao',
    'baccala',
    'haddock',
    'hake',
    'pollock',
    'pollack',
    'coley',
    'whiting',
    'halibut',
    'plaice',
    'sole',
    'turbot',
    'brill',
    'dory',
    'tilapia',
    'catfish',
    'carp',
    'perch',
    'pike',
    'zander',
    'bass',
    'seabass',
    'bream',
    'snapper',
    'grouper',
    'mullet',
    'monkfish',
    'swordfish',
    'marlin',
    'mahi mahi',
    'barramundi',
    'basa',
    'pangasius',
    'eel',
    'skate',
    'whitebait',
    'smelt',
    'shad',
    'lox',
    'gravlax',
    'surimi',
    'bombay duck',
    // Roe.
    'roe',
    'caviar',
    'ikura',
    'tobiko',
    'bottarga',
    'taramasalata',
    // Shellfish and other seafood.
    'shrimp',
    'prawn',
    'scampi',
    'langoustine',
    'crayfish',
    'crawfish',
    'crab',
    'crabmeat',
    'lobster',
    'krill',
    'mussel',
    'clam',
    'cockle',
    'oyster',
    'scallop',
    'whelk',
    'winkle',
    'periwinkle',
    'conch',
    'abalone',
    'squid',
    'calamari',
    'octopus',
    'cuttlefish',
    'sea urchin',
    'sea cucumber',
    'jellyfish',
    // Sauces, pastes and stocks with fish in them.
    'nam pla',
    'nuoc mam',
    'nuoc cham',
    'patis',
    'colatura',
    'garum',
    'worcestershire',
    'worcester sauce',
    'worchestershire',
    'belacan',
    'blachan',
    'terasi',
    'kapi',
    'bagoong',
    'prahok',
    'katsuobushi',
    'dashi',
    'hondashi',
    'gentlemans relish',
    // Caesar dressing, kimchi and tapenade are usually made with anchovy, fish sauce or shrimp.
    'caesar',
    'kimchi',
    'tapenade',
    'xo sauce',
    'isinglass',
    // Thai-style curry pastes and chili jam are made with shrimp paste or dried shrimp.
    'curry paste',
    'laksa paste',
    'tom yum paste',
    'nam prik pao',
    'thai chili jam',
    'thai chilli jam',
  ],
  exceptions: [
    'oyster mushroom',
    'crab apple',
    'fish seasoning',
    'fish pepper',
    'fish mint',
    'caviar lime',
    'eggplant caviar',
    'aubergine caviar',
    'kombu dashi',
    'shiitake dashi',
    'mushroom dashi',
    // Labelled vegetarian, and a plain plant sauce rather than a fish stand-in.
    'vegetarian worcestershire',
  ],
  neutralizers: ['vegetarian', 'vegan', 'veggie', 'fish free', 'plant based'],
} as const satisfies CategoryKeywords

/** Milk from animals and everything made from it. */
const DAIRY = {
  keywords: [
    'milk',
    'buttermilk',
    'cream',
    'creamer',
    'half and half',
    'butter',
    'buttered',
    'buttery',
    'beurre',
    'ghee',
    'samna',
    'smen',
    'margarine',
    'whey',
    'casein',
    'caseinate',
    'lactose',
    'malai',
    'khoya',
    'khoa',
    'mawa',
    'chhena',
    // Cultured milk.
    'yogurt',
    'yoghurt',
    'yogourt',
    'laban',
    'labneh',
    'labne',
    'labaneh',
    'ayran',
    'kashk',
    'kishk',
    'skyr',
    'kefir',
    'quark',
    'curd',
    'creme fraiche',
    'fromage',
    // Cheese.
    'cheese',
    'cheddar',
    'mozzarella',
    'mozarella',
    'parmesan',
    'parmigiano',
    'reggiano',
    'grana padano',
    'pecorino',
    'ricotta',
    'mascarpone',
    'feta',
    'halloumi',
    'hellim',
    'paneer',
    'queso',
    'cotija',
    'burrata',
    'stracciatella',
    'brie',
    'camembert',
    'stilton',
    'roquefort',
    'gorgonzola',
    'dolcelatte',
    'taleggio',
    'fontina',
    'provolone',
    'asiago',
    'emmental',
    'emmentaler',
    'emmenthal',
    'gruyere',
    'comte',
    'raclette',
    'reblochon',
    'jarlsberg',
    'gouda',
    'edam',
    'manchego',
    'monterey jack',
    'pepper jack',
    'colby',
    'havarti',
    'wensleydale',
    'red leicester',
    'double gloucester',
    'vasterbottensost',
    'bryndza',
    'akkawi',
    'ackawi',
    'nabulsi',
    'kashkaval',
    'kasseri',
    'kefalotyri',
    'kefalograviera',
    'graviera',
    'mizithra',
    'myzithra',
    'jibneh',
    'gebna',
    'gibna',
    'domiati',
    'rumi',
    'roumi',
    'mish',
    'shanklish',
    // Sweets usually made with milk, butter or cream.
    'custard',
    'ice cream',
    'gelato',
    'kulfi',
    'dulce de leche',
    'cajeta',
    'chocolate',
    'nutella',
    'hazelnut spread',
    'caramel',
    'toffee',
    'fudge',
    'butterscotch',
    'mars bar',
    'cheesecake',
    'shortbread',
    'christmas pudding',
    // Sauces and dressings built on dairy.
    'pesto',
    'bechamel',
    'white sauce',
    'alfredo',
    'hollandaise',
    'bearnaise',
    'tzatziki',
    'raita',
    'ranch dressing',
    'caesar',
    'creamed spinach',
    'creamed horseradish',
    'horseradish sauce',
    // Breads, pastry and batters usually made with butter or milk.
    'naan',
    'brioche',
    'croissant',
    'pain au chocolat',
    'pastry',
    'pancake',
    'crepe',
    'waffle',
    'yorkshire pudding',
    'cake',
    'knafeh',
    'kunafa',
    'kunafeh',
    'kanafeh',
    'tequeno',
    // Filled pasta: the filling is usually cheese when no meat is named.
    'tortellini',
    'ravioli',
    'cappelletti',
    'agnolotti',
  ],
  exceptions: [
    // Plant milks, creams and yogurts.
    'coconut milk',
    'coconut condensed milk',
    'coconut cream',
    'coconut yogurt',
    'coconut yoghurt',
    'almond milk',
    'almond yogurt',
    'almond yoghurt',
    'soy milk',
    'soya milk',
    'soy cream',
    'soya cream',
    'soy yogurt',
    'soya yogurt',
    'soy yoghurt',
    'soya yoghurt',
    'oat milk',
    'oat cream',
    'oat yogurt',
    'oat yoghurt',
    'rice milk',
    'cashew milk',
    'cashew cream',
    'hazelnut milk',
    'hemp milk',
    'pea milk',
    'macadamia milk',
    'nut milk',
    'plant milk',
    'vegetable milk',
    // Nut, seed and fruit butters, and plants named after butter.
    'peanut butter',
    'almond butter',
    'cashew butter',
    'hazelnut butter',
    'nut butter',
    'seed butter',
    'sunflower butter',
    'soy butter',
    'coconut butter',
    'palm butter',
    'cocoa butter',
    'cacao butter',
    'shea butter',
    'apple butter',
    'butter bean',
    'butternut',
    'butter lettuce',
    // Not dairy despite the name.
    'cream of tartar',
    'custard powder',
    'bean curd',
    'milk thistle',
    'rice cake',
    // Filo-type pastry is made without butter (any butter is listed separately).
    'filo pastry',
    'phyllo pastry',
    'fillo pastry',
    'brik pastry',
    'brick pastry',
  ],
  // "Non-dairy" is deliberately absent: non-dairy creamers often contain casein.
  neutralizers: ['vegan', 'dairy free', 'milk free', 'plant based'],
} as const satisfies CategoryKeywords

/** Eggs and the sauces, doughs and desserts built on them. */
const EGG = {
  keywords: [
    'egg',
    'yolk',
    'albumen',
    'mayonnaise',
    'mayo',
    'aioli',
    'tartar sauce',
    'tartare sauce',
    'remoulade',
    'caesar',
    'ranch dressing',
    'hollandaise',
    'bearnaise',
    'meringue',
    'royal icing',
    'pavlova',
    'macaron',
    'nougat',
    'custard',
    'creme anglaise',
    'creme patissiere',
    'pastry cream',
    'lemon curd',
    'zabaglione',
    'sabayon',
    'eggnog',
    'ice cream',
    'brioche',
    'challah',
    'choux',
    'eclair',
    'profiterole',
    'ladyfinger',
    'lady finger',
    'savoiardi',
    'sponge finger',
    'swiss roll',
    'pancake',
    'crepe',
    'waffle',
    'yorkshire pudding',
    'cake',
    'christmas pudding',
    // Fresh and filled pasta is egg pasta.
    'fresh pasta',
    'fresh lasagne',
    'fresh lasagna',
    'fresh tagliatelle',
    'fresh fettuccine',
    'tortellini',
    'ravioli',
    'cappelletti',
    'agnolotti',
  ],
  exceptions: ['egg plant', 'flax egg', 'chia egg', 'egg replacer', 'custard powder', 'rice cake'],
  neutralizers: ['vegan', 'egg free', 'eggless', 'plant based'],
} as const satisfies CategoryKeywords

/** Other animal products that only vegans avoid (gelatin is meat, isinglass is fish). */
const ANIMAL = {
  keywords: [
    'honey',
    'honeycomb',
    'royal jelly',
    'bee pollen',
    'propolis',
    'beeswax',
    'carmine',
    'cochineal',
    'shellac',
  ],
  exceptions: ['honey mushroom'],
  neutralizers: ['vegan'],
} as const satisfies CategoryKeywords

/** Wheat, barley, rye, oats (not certified gluten-free) and products usually made with them. */
const GLUTEN = {
  keywords: [
    // Grains and flours.
    'wheat',
    'wheatgerm',
    'flour',
    'gluten',
    'seitan',
    'spelt',
    'farro',
    'emmer',
    'einkorn',
    'kamut',
    'triticale',
    'durum',
    'semolina',
    'farina',
    'barley',
    'rye',
    'malt',
    'malted',
    'oat',
    'oatmeal',
    'oatcake',
    'granola',
    'muesli',
    'bran',
    'bulgur',
    'bulghur',
    'burghul',
    'freekeh',
    'frikeh',
    'couscous',
    'cous cous',
    'fregola',
    'mixed grain',
    'kishk',
    'arabic rice',
    // Pasta and noodles.
    'pasta',
    'spaghetti',
    'macaroni',
    'penne',
    'fusilli',
    'farfalle',
    'rigatoni',
    'paccheri',
    'linguine',
    'fettuccine',
    'tagliatelle',
    'pappardelle',
    'lasagne',
    'lasagna',
    'cannelloni',
    'ravioli',
    'tortellini',
    'cappelletti',
    'agnolotti',
    'conchiglie',
    'orzo',
    'gnocchi',
    'vermicelli',
    'fideo',
    'sevaiya',
    'sevaiiya',
    'seviyan',
    'rishta',
    'noodle',
    'udon',
    'ramen',
    'soba',
    'lo mein',
    'chow mein',
    // Doughs, wrappers and pastry.
    'wonton',
    'dumpling',
    'gyoza',
    'pierogi',
    'empanada',
    'samosa',
    'spring roll',
    'egg roll',
    'wrapper',
    'pastry',
    'shortcrust',
    'filo',
    'phyllo',
    'fillo',
    'yufka',
    'kataifi',
    'kadaif',
    'knafeh',
    'kunafa',
    'kunafeh',
    'kanafeh',
    'brik',
    'warka',
    'warqa',
    'malsouka',
    'pie crust',
    'pizza dough',
    'pizza base',
    'pizza crust',
    'dough',
    'tart shell',
    'tart case',
    'vol au vent',
    'choux',
    'pate brisee',
    'pate sucree',
    'pate feuilletee',
    'eclair',
    'profiterole',
    'tequeno',
    // Bread.
    'bread',
    'sourdough',
    'breadcrumb',
    'breadstick',
    'panko',
    'crouton',
    'toast',
    'pita',
    'pitta',
    'naan',
    'chapati',
    'roti',
    'paratha',
    'lavash',
    'markook',
    'flatbread',
    'tortilla',
    'wrap',
    'bun',
    'bagel',
    'baguette',
    'ciabatta',
    'focaccia',
    'brioche',
    'challah',
    'croissant',
    'pain au chocolat',
    'muffin',
    'crumpet',
    'scone',
    'pretzel',
    'stuffing',
    'matzo',
    'matzah',
    'matzoh',
    // Biscuits, cakes and batters.
    'cracker',
    'crispbread',
    'biscuit',
    'cookie',
    'shortbread',
    'gingerbread',
    'cornbread',
    'digestive',
    'graham',
    'ginger nut',
    'gingernut',
    'wafer',
    'cake',
    'cheesecake',
    'sponge',
    'swiss roll',
    'ladyfinger',
    'lady finger',
    'savoiardi',
    'pancake',
    'crepe',
    'waffle',
    'yorkshire pudding',
    'christmas pudding',
    'roux',
    'bechamel',
    'white sauce',
    'batter',
    'battered',
    'breaded',
    'tempura',
    // Malted cereals and sweets.
    'cornflake',
    'rice krispie',
    'grape nut',
    'mars bar',
    // Beer, and condiments brewed with wheat or barley or thickened with flour.
    'beer',
    'ale',
    'lager',
    'stout',
    'guinness',
    'marmite',
    'vegemite',
    'soy sauce',
    'shoyu',
    'teriyaki',
    'hoisin',
    'kecap manis',
    'ketjap manis',
    'ponzu',
    'black bean sauce',
    'oyster sauce',
    'worcestershire',
    'worcester sauce',
    'worchestershire',
    'brown sauce',
    'gochujang',
    'doubanjiang',
    'chili bean paste',
    'chilli bean paste',
    'miso',
    'shaoxing',
    'english mustard',
    'mustard powder',
    'enchilada sauce',
    'curry paste',
    'laksa paste',
    'tom yum paste',
    // Stocks, gravies and cubes often contain wheat.
    'stock',
    'broth',
    'bouillon',
    'consomme',
    'gravy',
    'oxo',
    'bovril',
    // Meat products usually bound with rusk, breadcrumbs, bulgur, oats or flour-coated suet.
    'sausage',
    'chipolata',
    'black pudding',
    'white pudding',
    'haggis',
    'meatball',
    'meatloaf',
    'burger',
    'doner',
    'gyro',
    'kibbeh',
    'suet',
    'mincemeat',
    'mock duck',
    'mock meat',
  ],
  exceptions: [
    // Gluten-free flours and starches.
    'rice flour',
    'corn flour',
    'maize flour',
    'chickpea flour',
    'gram flour',
    'almond flour',
    'coconut flour',
    'buckwheat flour',
    'tapioca flour',
    'potato flour',
    'sorghum flour',
    'teff flour',
    'millet flour',
    'cassava flour',
    'arrowroot flour',
    'quinoa flour',
    'chestnut flour',
    'banana flour',
    'plantain flour',
    'amaranth flour',
    'lentil flour',
    'pea flour',
    'fava bean flour',
    'soy flour',
    'soya flour',
    'peanut flour',
    'hazelnut flour',
    'tiger nut flour',
    // Rice, bean and vegetable noodles and wrappers.
    'rice noodle',
    'rice vermicelli',
    'vermicelli rice noodle',
    'rice stick',
    'rice stick noodle',
    'rice vermicelli noodle',
    'bean thread',
    'rice paper',
    'rice pasta',
    'corn pasta',
    'chickpea pasta',
    'lentil pasta',
    'quinoa pasta',
    'glass noodle',
    'cellophane noodle',
    'bean thread noodle',
    'mung bean noodle',
    'sweet potato noodle',
    'kelp noodle',
    'konjac noodle',
    'shirataki noodle',
    'zucchini noodle',
    'courgette noodle',
    'corn tortilla',
    'lettuce wrap',
    'rice cracker',
    'prawn cracker',
    'shrimp cracker',
    'rice cake',
    'rice bran',
    // Not grain products despite the name.
    'gingerbread spice',
    'gyro seasoning',
    'pasta sauce',
    'spaghetti sauce',
    'spaghetti squash',
    'cauliflower couscous',
    'sponge gourd',
    'root beer',
    'ginger beer',
    'ginger ale',
  ],
  neutralizers: ['gluten free', 'tamari'],
} as const satisfies CategoryKeywords

/**
 * Meat and fish stand-ins. A 'vegetarian' or 'meat free' label promises no meat or fish and nothing
 * more: a vegetarian sausage, veggie burger or meat-free mince is often bound with egg white, holds
 * cheese or is made from wheat or barley (Quorn is). So the labels are MEAT and FISH neutralizers
 * only, and a meat or fish word under one of them (or a stand-in named without one) falls into
 * every one of `categories` unless a vegan, plant-based, egg-free, dairy-free or gluten-free label
 * clears it. 'Vegan sausage' therefore stays vegan; 'vegetarian sausage' is only vegetarian.
 */
export const MEAT_STAND_INS = {
  /** Labels that make any meat or fish word a stand-in: 'vegetarian bacon', 'meatless meatball'. */
  labels: ['vegetarian', 'veggie', 'meat free', 'meatless', 'fish free'],
  /** Stand-ins named without such a label. */
  products: ['quorn', 'bean burger', 'mushroom burger', 'meat substitute', 'meat alternative'],
  categories: ['dairy', 'egg', 'gluten'],
} as const satisfies {
  labels: PhraseList
  products: PhraseList
  categories: readonly DietCategory[]
}

export const DIET_KEYWORDS = {
  meat: MEAT,
  fish: FISH,
  dairy: DAIRY,
  egg: EGG,
  animal: ANIMAL,
  gluten: GLUTEN,
} as const satisfies Record<DietCategory, CategoryKeywords>
