/**
 * Measurement, container and portion words that can sit in front of an ingredient name
 * ("2 tbsp", "1 can", "a pinch of"). The English normalizer only strips them as whole tokens at the
 * start of a phrase or right after a quantity, so "Bulb" never loses its "lb" and "Mars Bar" keeps
 * its "bar".
 */
export const UNIT_WORDS: ReadonlySet<string> = new Set([
  // Volume
  'cup',
  'cups',
  'tbsp',
  'tbsps',
  'tbs',
  'tbl',
  'tbls',
  'tblsp',
  'tblspn',
  'tbspn',
  'tablespoon',
  'tablespoons',
  'tsp',
  'tsps',
  'tspn',
  'teaspoon',
  'teaspoons',
  'teaspoonful',
  'teaspoonfuls',
  'tablespoonful',
  'tablespoonfuls',
  'c',
  'ml',
  'mls',
  'millilitre',
  'millilitres',
  'milliliter',
  'milliliters',
  'cl',
  'dl',
  'l',
  'ltr',
  'litre',
  'litres',
  'liter',
  'liters',
  'fl',
  'floz',
  'pint',
  'pints',
  'pt',
  'quart',
  'quarts',
  'qt',
  'gallon',
  'gallons',
  'gal',
  'gals',
  // Mass
  'g',
  'gr',
  'grs',
  'gm',
  'gms',
  'gram',
  'grams',
  'gramme',
  'grammes',
  'kg',
  'kgs',
  'kilo',
  'kilos',
  'kilogram',
  'kilograms',
  'mg',
  'oz',
  'ozs',
  'ounce',
  'ounces',
  'lb',
  'lbs',
  'pound',
  'pounds',
  // Length (for "2.5cm piece of ginger")
  'cm',
  'mm',
  'inch',
  'inches',
  // Vague amounts
  'pinch',
  'pinches',
  'dash',
  'dashes',
  'splash',
  'splashes',
  'drizzle',
  'drop',
  'drops',
  'handful',
  'handfuls',
  'handfull',
  'handfulls',
  'knob',
  'knobs',
  'sprinkle',
  'sprinkling',
  'sprinking',
  'spinkling',
  'scoop',
  'scoops',
  'glug',
  'glugs',
  'shot',
  'shots',
  // Containers and portions
  'can',
  'cans',
  'tin',
  'tins',
  'jar',
  'jars',
  'packet',
  'packets',
  'pack',
  'packs',
  'package',
  'packages',
  'pkg',
  'pkt',
  'pkts',
  'pk',
  'doz',
  'bag',
  'bags',
  'box',
  'boxes',
  'bottle',
  'bottles',
  'carton',
  'cartons',
  'tub',
  'tubs',
  'pot',
  'pots',
  'sachet',
  'sachets',
  'envelope',
  'envelopes',
  'block',
  'blocks',
  'bar',
  'bars',
  'bunch',
  'bunches',
  'sprig',
  'sprigs',
  'stick',
  'sticks',
  'stalk',
  'stalks',
  'slice',
  'slices',
  'piece',
  'pieces',
  'part',
  'parts',
  'floret',
  'florets',
  'pod',
  'pods',
  'thumb',
  'grating',
  'pc',
  'pcs',
  'head',
  'heads',
  'bulb',
  'bulbs',
  'rasher',
  'rashers',
  'sheet',
  'sheets',
  'fillet',
  'fillets',
  'strip',
  'strips',
  'cube',
  'cubes',
  'chunk',
  'chunks',
  'wedge',
  'wedges',
  'square',
  'squares',
  'ear',
  'ears',
  'leaf',
  'leaves',
  'clove',
  'cloves',
])

/**
 * Units that are also ingredients or name a thing on their own: "3 cloves" and "Cloves" mean the
 * spice, "2 cloves garlic" means garlic. They are stripped only when another word follows them.
 */
export const NOUN_UNITS: ReadonlySet<string> = new Set([
  'clove',
  'cloves',
  'leaf',
  'leaves',
  'bulb',
  'bulbs',
])

/** Words that only size a following unit ("1 heaped tbsp", "2 large cloves garlic"). */
export const UNIT_MODIFIERS: ReadonlySet<string> = new Set([
  'heaped',
  'heaping',
  'level',
  'rounded',
  'scant',
  'generous',
  'good',
  'large',
  'small',
  'medium',
  'big',
  'little',
  'lg',
  'lrg',
  'med',
  'sm',
  'thick',
  'thin',
  'thumb-sized',
  'thumb-size',
  'bite-sized',
])

/** Spelled-out amounts and approximations that open a phrase ("a pinch", "half a lemon"). */
export const QUANTITY_WORDS: ReadonlySet<string> = new Set([
  'a',
  'an',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'half',
  'quarter',
  'third',
  'dozen',
  'couple',
  'few',
  'several',
  'some',
  'about',
  'approx',
  'approximately',
  'around',
  'up',
])

/** Glue words between quantities, units and the name ("2 x 400g", "2 to 3", "a pinch of"). */
export const QUANTITY_JOINERS: ReadonlySet<string> = new Set(['x', 'to', 'or', '-', '/', '+'])

/**
 * Words that add a second amount to the first ("1 cup plus 2 tbsp", "1 and 1/2 cups", "one and a
 * half"). Skipped only between an amount and another number, amount word or unit, so "salt and
 * pepper" and "2 tomatoes and 1 onion" keep theirs.
 */
export const AMOUNT_LINKS: ReadonlySet<string> = new Set(['and', 'plus'])
